const translations = {
  en: {
    "meta.title": "Ma Chen | AI Product Portfolio",
    "meta.description": "Ma Chen portfolio: AI product management, multilingual localization, agent workflows, and refined digital product case studies.",
    "nav.about": "About",
    "nav.projects": "Projects",
    "nav.experience": "Experience",
    "nav.process": "Process",
    "nav.contact": "Contact",
    "hero.eyebrow": "AI product manager · multilingual systems · crafted interfaces",
    "hero.titleA": "Designing AI products",
    "hero.titleB": "that feel local, useful, and alive.",
    "hero.lead": "I connect user research, language strategy, prompt systems, and front-end storytelling to turn complex AI workflows into polished product experiences.",
    "hero.ctaPrimary": "Explore projects",
    "hero.ctaSecondary": "Start a conversation",
    "hero.photoAlt": "Portrait of Ma Chen",
    "hero.signal": "Open to AI PM and product localization roles",
    "metrics.interviews": "user interviews",
    "metrics.samples": "UGC samples reviewed",
    "metrics.languages": "working languages",
    "about.eyebrow": "Profile",
    "about.title": "A product mind built between language, culture, and AI tooling.",
    "about.p1": "My background spans Spanish linguistics, digital humanities, AIGC globalization, content safety, and AI language companions.",
    "about.p2": "I like products where the interface is calm, the system is rigorous, and the user can feel that someone cared about the last ten percent.",
    "projects.eyebrow": "Selected work",
    "projects.title": "Two product worlds, each given room to breathe.",
    "projects.sub": "Full-screen chapters reveal the product story as you scroll: problem, interface logic, key features, and the delivery thinking behind each launch.",
    "project.detail": "View how it was made",
    "project.live": "Open live project",
    "project1.kicker": "Community product · MBTI discussion",
    "project1.title": "MBTI Discussion",
    "project1.lead": "A personality-type discussion experience designed around expressive identity, structured debate, and lightweight community participation.",
    "project1.f1": "Type-based exploration",
    "project1.f2": "Discussion-first information architecture",
    "project1.f3": "Identity cues and social entry points",
    "project2.kicker": "AI-native creative experiment · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "A pixel-alien desktop-pet universe with character lore, a visual planet, and an indie product loop powered by AI-assisted production.",
    "project2.f1": "Character system and worldbuilding",
    "project2.f2": "Character lore and story system",
    "project2.f3": "Playful web visualization",
    "project3.kicker": "AI language companion · Spanish model",
    "project3.title": "AI Language Companion",
    "project3.lead": "A Spanish language-companion model project focused on conversation quality, localization judgment, tutoring scenarios, and evaluation loops.",
    "project3.f1": "Spanish conversation model",
    "project3.f2": "Scenario and persona design",
    "project3.f3": "Localization QA loop",
    "experience.eyebrow": "Experience",
    "experience.title": "Professional and academic foundations behind the product work.",
    "experience.proLabel": "Professional",
    "experience.proTitle": "AI product, localization, and content safety",
    "experience.proText": "Work across AI language companions, AIGC globalization, user research, UGC evaluation, and multilingual product definition.",
    "experience.eduLabel": "Education",
    "experience.eduTitle": "Digital humanities and Spanish language background",
    "experience.eduText": "Training in Spanish linguistics, digital humanities, corpora, semantic web, visualization, and cross-cultural analysis.",
    "experience.toolLabel": "Tooling",
    "experience.toolTitle": "AI-assisted product execution",
    "experience.toolText": "Hands-on production with Codex, Claude Code, prompt workflows, structured knowledge bases, Figma, Notion, SQL, and data tools.",
    "process.eyebrow": "Method",
    "process.title": "How I shape product work from ambiguity to release.",
    "process.s1Title": "Frame the real problem",
    "process.s1Text": "Map users, scenarios, motivation, cultural context, and the emotional friction behind the request.",
    "process.s2Title": "Prototype the experience",
    "process.s2Text": "Translate insights into flows, prompts, content rules, and interface states that can be tested quickly.",
    "process.s3Title": "Build the operating system",
    "process.s3Text": "Define QA loops, localization logic, release phases, and measurable signals before scaling.",
    "contact.eyebrow": "Contact",
    "contact.title": "Let’s build AI products that feel carefully made.",
    "contact.resume": "Download resume",
    "case.back": "Back to portfolio",
    "case.live": "Open live project",
    "case.overview": "Overview",
    "case.phases": "Project phases",
    "case.architecture": "Product architecture",
    "case.execution": "Execution notes",
    "case.role": "My role",
    "case.decisions": "Key decisions",
    "case.outcome": "Outcome",
    "mbti.metaTitle": "MindPalace MBTI Discussion | Ma Chen",
    "mbti.metaDescription": "MindPalace / MBTI Discussion case study by Ma Chen: a multi-agent reflection table for emotion and relationship topics.",
    "mbti.kicker": "Case study · MBTI Discussion",
    "mbti.title": "MindPalace: a multi-agent reflection table for MBTI discussion.",
    "mbti.lead": "Users enter an emotion or relationship topic, then four AI agents respond from NT, NF, SJ, and SP perspectives before debating with each other in a second round.",
    "mbti.overviewTitle": "Product lens",
    "mbti.overviewText": "MindPalace is a personal AI roundtable web app. It turns private emotional questions into structured multi-perspective reflection, showing the full discussion timeline so users can compare viewpoints instead of receiving a single answer.",
    "mbti.roleText": "I owned the product definition and delivery path: PRD, user flow, technical architecture, design rules, operations runbook, AI agent setup, front-end implementation, database connection, and Netlify deployment.",
    "mbti.decision1": "Defined the core scenario as a multi-perspective emotional reflection tool: users enter an emotion or relationship topic and receive independent responses from NT, NF, SJ, and SP thinking dimensions.",
    "mbti.decision2": "Designed a two-round discussion mechanism: the first round lets four agents respond independently, while the second round asks them to supplement and challenge each other based on the user's question and the first responses.",
    "mbti.decision3": "Used Claude Code / Cursor to turn product documents into a working web app with Next.js, TypeScript, Tailwind, API routes, Prisma, Supabase, DeepSeek API calls, and streamed output.",
    "mbti.executionTitle": "Execution notes",
    "mbti.executionText": "The system uses strong typographic hierarchy, compact personality cues, and visual rhythm to keep a discussion product from feeling like a generic forum. The design direction favors clear category structures, expressive type badges, and short paths to participation.",
    "mbti.architectureTitle": "Product architecture",
    "mbti.architectureText": "The product is structured around three layers: personality discovery, discussion contexts, and lightweight community actions. This makes the user journey more intentional than a simple feed and gives the product a stronger reason to exist.",
    "mbti.outcomeTitle": "Outcome",
    "mbti.outcomeText": "Validated my ability to ship a product from 0 to 1 with an AI toolchain, covering requirement definition, interaction design, AI agent orchestration, front-end/back-end development, database setup, deployment, and maintenance workflow. The project also clarified a reusable vibe-coding method: constrain AI coding agents with PRDs and decision documents, manage product boundaries through documentation, and iterate quickly toward a usable online prototype.",
    "mbti.phase1Title": "Research the conversation model",
    "mbti.phase1Text": "Identify what users expect from MBTI communities: self-expression, comparison, debate, and lightweight discovery.",
    "mbti.phase2Title": "Define the product structure",
    "mbti.phase2Text": "Organize entry points around types, discussion topics, and community actions instead of a flat feed.",
    "mbti.phase3Title": "Design the interaction tone",
    "mbti.phase3Text": "Use personality labels as visual anchors while keeping the interface minimal, readable, and discussion-first.",
    "mbti.phase4Title": "Package the case",
    "mbti.phase4Text": "Present the project as a social product with clear feature logic, not just a visual experiment.",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "Lumi Galaxy case study by Ma Chen: an AI-native creative product with five pixel-alien desktop pets, character stories, and an interactive web world.",
    "lumi.kicker": "Case study · Lumi Galaxy",
    "lumi.title": "A character universe shaped into an AI-native product loop.",
    "lumi.lead": "Lumi Galaxy is a playful web world for pixel-alien desktop pets, combining character design, lore structure, and AI-assisted production.",
    "lumi.overviewTitle": "Product lens",
    "lumi.overviewText": "Lumi Galaxy is an AI-native creative product built around five pixel-style alien desktop pets. Each character has its own world setting, personality, story material, and interaction direction, finally packaged into a visual Starball web experience.",
    "lumi.roleText": "I independently defined and built the product from 0 to 1, including the five alien characters, world setting, interaction experience, feature priority, visual direction, front-end prototype, and iteration plan.",
    "lumi.decision1": "Positioned Lumi Galaxy as an AI-native creative desktop-pet universe rather than a static showcase, giving each character its own personality, story hook, and interaction promise.",
    "lumi.decision2": "Used AI tools to accelerate character background writing, pixel-art asset drafts, dialogue tone, front-end prototyping, and visual iteration while keeping the creative direction coherent.",
    "lumi.decision3": "Compressed the usual art-plus-copy production loop into a solo executable workflow, so product concept, content production, and web launch could move together.",
    "lumi.executionTitle": "Execution notes",
    "lumi.executionText": "The build is framed as a solo 0-to-1 workflow. AI tools support ideation, content structuring, web implementation, and iteration, while the product direction keeps a coherent visual language across the planet, characters, and lore.",
    "lumi.architectureTitle": "Product architecture",
    "lumi.architectureText": "The case combines a visual layer, a character layer, and a knowledge layer. That structure shows how the project can evolve from a portfolio website into a richer AI companion product with dialogue and persistence.",
    "lumi.outcomeTitle": "Outcome",
    "lumi.outcomeText": "Demonstrated the feasibility of using a pure AI toolchain to move from creative concept to a launched product prototype. The project shows solo 0-to-1 product shaping, AI-assisted content production, and the ability to turn a playful idea into a polished web artifact.",
    "lumi.phase1Title": "World and character definition",
    "lumi.phase1Text": "Create the personality system, lore rules, visual cues, and interaction promise for the pixel-alien universe.",
    "lumi.phase2Title": "Character content system",
    "lumi.phase2Text": "Structure character backgrounds, story fragments, visual cues, and dialogue tone so each alien feels distinct and memorable.",
    "lumi.phase3Title": "Visual product prototype",
    "lumi.phase3Text": "Turn the concept into a web experience with motion, planet metaphors, and a playful but controlled art direction.",
    "lumi.phase4Title": "Launch and iteration",
    "lumi.phase4Text": "Package the project as a shipped indie experiment and define the next loop: dialogue, retention, and richer character interaction.",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "AI Language Companion - Spanish Model case study by Ma Chen.",
    "workflow.kicker": "Case study · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "A Spanish conversation-model project focused on language-learning scenarios, tutoring tone, localization quality, and model evaluation loops.",
    "workflow.overviewTitle": "Product lens",
    "workflow.overviewText": "This case will document how a Spanish language-companion model is shaped through target user scenarios, tutoring persona definition, conversation quality standards, and bilingual localization review.",
    "workflow.phase1Title": "Define learning scenarios",
    "workflow.phase1Text": "Map practice contexts such as daily conversation, grammar correction, role-play, cultural explanation, and confidence building for Spanish learners.",
    "workflow.phase2Title": "Shape the model persona",
    "workflow.phase2Text": "Define the companion's tone, correction style, encouragement rules, and boundaries between tutor, conversation partner, and cultural explainer.",
    "workflow.phase3Title": "Build evaluation loops",
    "workflow.phase3Text": "Create review criteria for fluency, accuracy, empathy, level fit, cultural nuance, and recovery from user mistakes.",
    "workflow.phase4Title": "Package the case details",
    "workflow.phase4Text": "The detailed product artifacts, samples, and evaluation notes will be added in the next iteration.",
    "workflow.architectureTitle": "Model workflow",
    "workflow.architectureText": "The current structure is reserved for the model workflow: scenario input, persona rules, response generation, bilingual review, and iteration notes.",
    "workflow.executionTitle": "Execution notes",
    "workflow.executionText": "This page is intentionally kept as a project shell for now so more concrete Spanish model details can be added cleanly later.",
    "workflow.outcomeTitle": "Outcome",
    "workflow.outcomeText": "A reserved AI language-companion case page that can later hold model samples, scenario definitions, evaluation criteria, and localization decisions."
  },
  es: {
    "meta.title": "Ma Chen | Portfolio de Producto IA",
    "meta.description": "Portfolio de Ma Chen: product management de IA, localización multilingüe, workflows con agentes y casos de producto digital.",
    "nav.about": "Perfil",
    "nav.projects": "Proyectos",
    "nav.experience": "Experiencia",
    "nav.process": "Método",
    "nav.contact": "Contacto",
    "hero.eyebrow": "Product manager IA · sistemas multilingües · interfaces cuidadas",
    "hero.titleA": "Diseño productos IA",
    "hero.titleB": "útiles, locales y memorables.",
    "hero.lead": "Conecto investigación de usuarios, estrategia lingüística, sistemas de prompt y narrativa visual para convertir workflows complejos de IA en experiencias de producto pulidas.",
    "hero.ctaPrimary": "Ver proyectos",
    "hero.ctaSecondary": "Hablemos",
    "hero.photoAlt": "Retrato de Ma Chen",
    "hero.signal": "Abierta a roles de AI PM y localización de producto",
    "metrics.interviews": "entrevistas a usuarios",
    "metrics.samples": "muestras UGC evaluadas",
    "metrics.languages": "idiomas de trabajo",
    "about.eyebrow": "Perfil",
    "about.title": "Una mirada de producto construida entre lenguaje, cultura y herramientas de IA.",
    "about.p1": "Mi trayectoria combina lingüística hispánica, humanidades digitales, globalización AIGC, seguridad de contenido y productos de compañeros lingüísticos con IA.",
    "about.p2": "Me interesan los productos con una interfaz serena, un sistema riguroso y un nivel de detalle que haga sentir al usuario que alguien cuidó el último diez por ciento.",
    "market.eyebrow": "Alcance de mercado",
    "market.title": "Capacidad para trabajar en Europa, China y América Latina.",
    "market.text": "Fluidez lingüística, contexto cultural y criterio de localización para productos que necesitan viajar bien entre mercados.",
    "projects.eyebrow": "Trabajo seleccionado",
    "projects.title": "Tres mundos de producto, cada uno con espacio propio.",
    "projects.sub": "Capítulos a pantalla completa muestran la historia de cada proyecto: problema, lógica de interfaz, funcionalidades y decisiones de entrega.",
    "project.detail": "Ver cómo se construyó",
    "project.live": "Abrir proyecto online",
    "project1.kicker": "Producto comunitario · MBTI discussion",
    "project1.title": "MBTI Discussion",
    "project1.lead": "Una experiencia de discusión sobre tipos de personalidad diseñada alrededor de identidad, debate estructurado y participación ligera.",
    "project1.f1": "Exploración por tipo",
    "project1.f2": "Arquitectura centrada en conversación",
    "project1.f3": "Señales de identidad y entrada social",
    "project2.kicker": "Experimento creativo AI-native · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "Un universo de mascotas alienígenas pixel art con lore de personajes, planeta visual y un ciclo indie producido con apoyo de IA.",
    "project2.f1": "Sistema de personajes y worldbuilding",
    "project2.f2": "Sistema de personajes y relatos",
    "project2.f3": "Visualización web lúdica",
    "project3.kicker": "Compañero lingüístico IA · modelo español",
    "project3.title": "AI Language Companion",
    "project3.lead": "Un proyecto de modelo conversacional en español centrado en calidad de diálogo, criterio de localización, escenarios de aprendizaje y ciclos de evaluación.",
    "project3.f1": "Modelo conversacional español",
    "project3.f2": "Diseño de escenarios y persona",
    "project3.f3": "QA de localización",
    "experience.eyebrow": "Experiencia",
    "experience.title": "Base profesional y académica detrás del trabajo de producto.",
    "experience.proLabel": "Profesional",
    "experience.proTitle": "Producto IA, localización y seguridad de contenido",
    "experience.proText": "Trabajo en AI language companions, globalización AIGC, investigación de usuarios, evaluación UGC y definición de producto multilingüe.",
    "experience.eduLabel": "Educación",
    "experience.eduTitle": "Humanidades digitales y formación en español",
    "experience.eduText": "Formación en lingüística hispánica, humanidades digitales, corpus, web semántica, visualización y análisis intercultural.",
    "experience.toolLabel": "Herramientas",
    "experience.toolTitle": "Ejecución de producto asistida por IA",
    "experience.toolText": "Producción práctica con Codex, Claude Code, workflows de prompts, bases de conocimiento estructuradas, Figma, Notion, SQL y herramientas de datos.",
    "process.eyebrow": "Método",
    "process.title": "Cómo llevo una necesidad ambigua hasta un producto publicable.",
    "process.s1Title": "Definir el problema real",
    "process.s1Text": "Mapeo usuarios, escenarios, motivación, contexto cultural y la fricción emocional detrás de la necesidad.",
    "process.s2Title": "Prototipar la experiencia",
    "process.s2Text": "Transformo insights en flujos, prompts, reglas de contenido y estados de interfaz que se pueden probar rápido.",
    "process.s3Title": "Construir el sistema de entrega",
    "process.s3Text": "Defino ciclos de QA, lógica de localización, fases de lanzamiento y señales medibles antes de escalar.",
    "contact.eyebrow": "Contacto",
    "contact.title": "Construyamos productos IA que se sientan cuidadosamente hechos.",
    "contact.resume": "Descargar CV",
    "case.back": "Volver al portfolio",
    "case.live": "Abrir proyecto online",
    "case.overview": "Resumen",
    "case.phases": "Fases del proyecto",
    "case.architecture": "Arquitectura de producto",
    "case.execution": "Ejecución",
    "case.role": "Mi rol",
    "case.decisions": "Decisiones clave",
    "case.outcome": "Resultado",
    "mbti.metaTitle": "MindPalace MBTI Discussion | Ma Chen",
    "mbti.metaDescription": "Caso de MindPalace / MBTI Discussion de Ma Chen: una mesa de reflexión multiagente para temas emocionales y relacionales.",
    "mbti.kicker": "Caso · MBTI Discussion",
    "mbti.title": "MindPalace: una mesa de reflexión multiagente para discusión MBTI.",
    "mbti.lead": "El usuario introduce un tema emocional o relacional; cuatro agentes IA responden desde perspectivas NT, NF, SJ y SP, y luego debaten entre sí en una segunda ronda.",
    "mbti.overviewTitle": "Mirada de producto",
    "mbti.overviewText": "MindPalace es una aplicación web de mesa redonda IA personal. Convierte preguntas emocionales privadas en reflexión multiperspectiva estructurada y muestra la línea temporal completa de discusión para comparar puntos de vista.",
    "mbti.roleText": "Me encargué de la definición de producto y la ruta de entrega: PRD, flujo de usuario, arquitectura técnica, reglas de diseño, runbook operativo, configuración de agentes IA, implementación front-end, conexión de base de datos y despliegue en Netlify.",
    "mbti.decision1": "Definí el escenario principal como una herramienta de reflexión emocional multiperspectiva: el usuario introduce un tema y recibe respuestas independientes desde cuatro dimensiones de pensamiento.",
    "mbti.decision2": "Diseñé un mecanismo de discusión en dos rondas: primero cuatro agentes responden de forma independiente; después se complementan y refutan entre sí a partir de la pregunta y las respuestas iniciales.",
    "mbti.decision3": "Usé Claude Code / Cursor para convertir documentación de producto en una app funcional con Next.js, TypeScript, Tailwind, API routes, Prisma, Supabase, llamadas a DeepSeek API y salida en streaming.",
    "mbti.executionTitle": "Ejecución",
    "mbti.executionText": "El sistema usa jerarquía tipográfica, señales compactas de personalidad y ritmo visual para evitar que un producto de discusión parezca un foro genérico. La dirección prioriza categorías claras, badges expresivos y rutas cortas hacia la participación.",
    "mbti.architectureTitle": "Arquitectura de producto",
    "mbti.architectureText": "El producto se estructura en tres capas: descubrimiento de personalidad, contextos de discusión y acciones comunitarias ligeras. Esto vuelve el recorrido más intencional que un feed simple y refuerza la razón de ser del producto.",
    "mbti.outcomeTitle": "Resultado",
    "mbti.outcomeText": "Validó mi capacidad de lanzar un producto 0 a 1 con una cadena de herramientas IA, cubriendo definición de requisitos, interacción, orquestación de agentes, front-end/back-end, base de datos, despliegue y mantenimiento. También consolidó un método de vibe coding basado en PRD, documentos de decisión y límites de producto claros.",
    "mbti.phase1Title": "Investigar el modelo conversacional",
    "mbti.phase1Text": "Identificar qué esperan los usuarios de comunidades MBTI: autoexpresión, comparación, debate y descubrimiento ligero.",
    "mbti.phase2Title": "Definir la estructura del producto",
    "mbti.phase2Text": "Organizar entradas por tipos, temas y acciones comunitarias en lugar de depender de un feed plano.",
    "mbti.phase3Title": "Diseñar el tono de interacción",
    "mbti.phase3Text": "Usar etiquetas de personalidad como anclas visuales manteniendo una interfaz mínima, legible y centrada en discusión.",
    "mbti.phase4Title": "Empaquetar el caso",
    "mbti.phase4Text": "Presentar el proyecto como un producto social con lógica funcional clara, no solo como un experimento visual.",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "Caso de Lumi Galaxy de Ma Chen: producto creativo AI-native con cinco mascotas alienígenas pixel art, historias de personajes y mundo web interactivo.",
    "lumi.kicker": "Caso · Lumi Galaxy",
    "lumi.title": "Un universo de personajes convertido en un ciclo de producto AI-native.",
    "lumi.lead": "Lumi Galaxy es un mundo web de mascotas alienígenas pixel art que combina diseño de personajes, estructura de lore y producción asistida por IA.",
    "lumi.overviewTitle": "Mirada de producto",
    "lumi.overviewText": "Lumi Galaxy es un producto creativo AI-native alrededor de cinco mascotas alienígenas pixel art. Cada personaje tiene mundo, personalidad, historia e interacción propia, empaquetado en una experiencia web visual Starball.",
    "lumi.roleText": "Definí y construí de forma independiente el producto de 0 a 1: cinco personajes alienígenas, mundo narrativo, experiencia de interacción, prioridades funcionales, dirección visual, prototipo front-end y plan de iteración.",
    "lumi.decision1": "Posicioné Lumi Galaxy como un universo creativo de mascotas de escritorio AI-native, no como una vitrina estática, para que cada personaje tuviera personalidad, gancho narrativo y promesa de interacción.",
    "lumi.decision2": "Usé herramientas IA para acelerar historias de personajes, borradores visuales pixel art, tono de diálogo, prototipado front-end e iteración visual manteniendo una dirección creativa coherente.",
    "lumi.decision3": "Comprimí el ciclo habitual de arte y copy en un flujo ejecutable por una sola persona, conectando concepto de producto, producción de contenido y lanzamiento web.",
    "lumi.executionTitle": "Ejecución",
    "lumi.executionText": "El proyecto está planteado como un flujo solo 0 a 1. Las herramientas de IA apoyan ideación, estructura de contenido, implementación web e iteración, mientras la dirección mantiene coherencia visual entre planeta, personajes y lore.",
    "lumi.architectureTitle": "Arquitectura de producto",
    "lumi.architectureText": "El caso combina una capa visual, una capa de personajes y una capa de conocimiento. Esa estructura muestra cómo puede evolucionar de portfolio web a producto de compañero IA con diálogo y persistencia.",
    "lumi.outcomeTitle": "Resultado",
    "lumi.outcomeText": "Demostró la viabilidad de usar una cadena de herramientas IA para pasar de concepto creativo a prototipo publicado. El proyecto muestra definición 0 a 1, producción de contenido asistida por IA y capacidad de convertir una idea lúdica en una pieza web pulida.",
    "lumi.phase1Title": "Definir mundo y personajes",
    "lumi.phase1Text": "Crear el sistema de personalidad, reglas de lore, señales visuales y promesa interactiva del universo pixel alien.",
    "lumi.phase2Title": "Sistema de contenido de personajes",
    "lumi.phase2Text": "Estructurar fondos de personaje, fragmentos de historia, señales visuales y tono de diálogo para que cada alien tenga una identidad clara.",
    "lumi.phase3Title": "Prototipo visual de producto",
    "lumi.phase3Text": "Convertir el concepto en una experiencia web con movimiento, metáforas planetarias y una dirección artística controlada.",
    "lumi.phase4Title": "Lanzamiento e iteración",
    "lumi.phase4Text": "Presentar el proyecto como experimento indie publicado y definir el siguiente ciclo: diálogo, retención e interacción más rica.",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "Caso de AI Language Companion - Spanish Model de Ma Chen.",
    "workflow.kicker": "Caso · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "Un proyecto de modelo conversacional en español centrado en escenarios de aprendizaje, tono tutorial, calidad de localización y ciclos de evaluación.",
    "workflow.overviewTitle": "Mirada de producto",
    "workflow.overviewText": "Este caso documentará cómo se define un modelo de compañero lingüístico en español mediante escenarios de usuario, persona tutorial, estándares de conversación y revisión bilingüe.",
    "workflow.phase1Title": "Definir escenarios de aprendizaje",
    "workflow.phase1Text": "Mapear prácticas como conversación diaria, corrección gramatical, role-play, explicación cultural y construcción de confianza.",
    "workflow.phase2Title": "Diseñar la persona del modelo",
    "workflow.phase2Text": "Definir tono, estilo de corrección, reglas de ánimo y límites entre tutor, compañero de conversación y explicador cultural.",
    "workflow.phase3Title": "Construir ciclos de evaluación",
    "workflow.phase3Text": "Crear criterios de revisión sobre fluidez, precisión, empatía, nivel del usuario, matiz cultural y recuperación ante errores.",
    "workflow.phase4Title": "Completar el caso",
    "workflow.phase4Text": "Los artefactos, muestras y notas de evaluación se añadirán en una siguiente iteración.",
    "workflow.architectureTitle": "Flujo del modelo",
    "workflow.architectureText": "La estructura queda reservada para el flujo del modelo: escenario, reglas de persona, generación, revisión bilingüe e iteración.",
    "workflow.executionTitle": "Ejecución",
    "workflow.executionText": "Esta página se mantiene como base de caso para añadir después detalles concretos del modelo español.",
    "workflow.outcomeTitle": "Resultado",
    "workflow.outcomeText": "Una página de caso reservada para incorporar muestras del modelo, escenarios, criterios de evaluación y decisiones de localización."
  },
  zh: {
    "meta.title": "马琛 | AI 产品作品集",
    "meta.description": "马琛的个人作品集：AI 产品管理、多语言本地化、Agent 工作流与高质感数字产品案例。",
    "nav.about": "关于",
    "nav.projects": "项目",
    "nav.experience": "经历",
    "nav.process": "方法",
    "nav.contact": "联系",
    "hero.eyebrow": "AI 产品经理 · 多语言系统 · 精致界面体验",
    "hero.titleA": "设计真正有用的",
    "hero.titleB": "AI 产品体验。",
    "hero.lead": "我把用户研究、语言策略、Prompt 系统与前端叙事连接起来，把复杂的 AI 工作流转化为清晰、专业、有温度的产品体验。",
    "hero.ctaPrimary": "浏览项目",
    "hero.ctaSecondary": "联系我",
    "hero.photoAlt": "马琛的个人照片",
    "hero.signal": "关注 AI PM 与产品本地化机会",
    "metrics.interviews": "用户深访",
    "metrics.samples": "UGC 样本评估",
    "metrics.languages": "工作语言",
    "about.eyebrow": "个人简介",
    "about.title": "一个建立在语言、文化与 AI 工具链之间的产品视角。",
    "about.p1": "我的经历横跨西班牙语语言学、数字人文、AIGC 出海、内容安全与 AI 语伴产品。",
    "about.p2": "我喜欢界面克制、系统严谨、并且能让用户感受到最后 10% 细节也被认真打磨过的产品。",
    "projects.eyebrow": "精选项目",
    "projects.title": "两个产品世界，各自拥有完整的展示空间。",
    "projects.sub": "页面会随着滚动展开项目故事：问题、界面逻辑、核心功能，以及每次发布背后的产品判断。",
    "project.detail": "查看项目如何完成",
    "project.live": "打开线上项目",
    "project1.kicker": "社区产品 · MBTI 讨论",
    "project1.title": "MBTI Discussion",
    "project1.lead": "一个围绕人格类型、身份表达、结构化讨论和轻量社区参与设计的讨论型产品体验。",
    "project1.f1": "基于类型的探索路径",
    "project1.f2": "讨论优先的信息架构",
    "project1.f3": "身份线索与社交入口",
    "project2.kicker": "AI 原生创意实验 · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "一个像素外星人桌面宠物宇宙，包含角色设定、视觉星球与 AI 辅助完成的独立产品闭环。",
    "project2.f1": "角色系统与世界观",
    "project2.f2": "角色故事与内容系统",
    "project2.f3": "带有玩味的网页可视化",
    "project3.kicker": "AI 语伴产品 · 西语模型",
    "project3.title": "AI Language Companion",
    "project3.lead": "一个围绕西语对话模型展开的 AI 语伴项目，关注学习场景、陪练语气、本地化质量与模型评估闭环。",
    "project3.f1": "西语对话模型",
    "project3.f2": "场景与 Persona 设计",
    "project3.f3": "本地化质检闭环",
    "experience.eyebrow": "经历",
    "experience.title": "支撑产品工作的职业与教育背景。",
    "experience.proLabel": "职业经验",
    "experience.proTitle": "AI 产品、本地化与内容安全",
    "experience.proText": "覆盖 AI 语伴、AIGC 出海、用户研究、UGC 评估与多语言产品定义。",
    "experience.eduLabel": "教育背景",
    "experience.eduTitle": "数字人文与西班牙语背景",
    "experience.eduText": "接受过西班牙语语言学、数字人文、语料库、语义网、可视化与跨文化分析训练。",
    "experience.toolLabel": "工具链",
    "experience.toolTitle": "AI 辅助产品执行",
    "experience.toolText": "实际使用 Codex、Claude Code、Prompt 工作流、结构化知识库、Figma、Notion、SQL 与数据工具完成项目。",
    "process.eyebrow": "方法",
    "process.title": "我如何把模糊需求推进到可发布的产品。",
    "process.s1Title": "定义真实问题",
    "process.s1Text": "梳理用户、场景、动机、文化语境，以及需求背后的情绪摩擦。",
    "process.s2Title": "快速原型体验",
    "process.s2Text": "把洞察转化为流程、Prompt、内容规则与可快速验证的界面状态。",
    "process.s3Title": "建立交付系统",
    "process.s3Text": "在规模化之前定义质检闭环、本地化逻辑、上线阶段与可衡量信号。",
    "contact.eyebrow": "联系",
    "contact.title": "一起做真正被认真打磨过的 AI 产品。",
    "contact.resume": "下载简历",
    "case.back": "返回作品集",
    "case.live": "打开线上项目",
    "case.overview": "项目概览",
    "case.phases": "项目阶段",
    "case.architecture": "产品架构",
    "case.execution": "执行说明",
    "case.role": "我的职责",
    "case.decisions": "关键决策",
    "case.outcome": "结果",
    "mbti.metaTitle": "MindPalace MBTI 讨论会 | Ma Chen",
    "mbti.metaDescription": "马琛的 MindPalace / MBTI 讨论会案例：围绕情感与关系话题的多 Agent 反思圆桌 Web 应用。",
    "mbti.kicker": "案例研究 · MBTI Discussion",
    "mbti.title": "MindPalace：一个多 Agent 情感反思圆桌。",
    "mbti.lead": "用户输入一个情感或关系类话题后，系统调用 NT / NF / SJ / SP 四个不同思维维度的 AI Agent，完成首轮独立回应与第二轮互相辩论。",
    "mbti.overviewTitle": "产品视角",
    "mbti.overviewText": "MindPalace 是一个个人 AI 圆桌 Web 应用。它把私密的情绪与关系问题转化为多视角结构化反思，并以时间线形式展示完整讨论过程，帮助用户获得比单一回答更丰富的判断。",
    "mbti.roleText": "我负责从产品定义到上线的完整链路，包括 PRD、用户流程、技术架构、设计规范、运维 Runbook、AI Agent 编排、前后端开发、数据库接入与 Netlify 部署。",
    "mbti.decision1": "从个人真实需求出发，将核心场景定义为“多视角情感反思工具”：用户输入情绪或关系话题后，由 NT / NF / SJ / SP 四类人格 Agent 分别回应。",
    "mbti.decision2": "设计“两阶段讨论机制”：首轮 4 个 Agent 独立回应，第二轮基于用户问题与全员首轮发言进行互相补充和反驳，保证上下文完整性与多视角表达质量。",
    "mbti.decision3": "使用 Claude Code / Cursor 等 AI 编程工具辅助完成 Next.js、TypeScript、Tailwind、API Route、Prisma、Supabase、DeepSeek API 调用与 SSE 流式输出等功能开发。",
    "mbti.executionTitle": "执行说明",
    "mbti.executionText": "系统通过强层级排版、紧凑的人格线索和节奏化视觉，避免讨论产品沦为普通论坛模板。设计方向强调清晰分类、类型标签和更短的参与路径。",
    "mbti.architectureTitle": "产品架构",
    "mbti.architectureText": "产品围绕三层结构展开：人格探索、讨论语境与轻量社区动作。这样用户路径会比普通信息流更有意图，也让产品本身具备更强的存在理由。",
    "mbti.outcomeTitle": "结果",
    "mbti.outcomeText": "验证了个人从 0 到 1 使用 AI 工具链完成产品上线的能力，覆盖需求定义、交互设计、AI 编排、前后端开发、数据库、部署与运维全流程。项目也沉淀了一套适合个人项目的 Vibe Coding 工作方式：以 PRD 和决策文档约束 AI 编程 Agent，用文档管理产品边界，用快速迭代完成可用原型上线。",
    "mbti.phase1Title": "研究讨论模型",
    "mbti.phase1Text": "识别用户对 MBTI 社区的期待：自我表达、比较、辩论和轻量探索。",
    "mbti.phase2Title": "定义产品结构",
    "mbti.phase2Text": "围绕类型、话题和社区动作组织入口，而不是简单的信息流。",
    "mbti.phase3Title": "设计交互语气",
    "mbti.phase3Text": "把人格标签作为视觉锚点，同时保持界面极简、可读并以讨论为核心。",
    "mbti.phase4Title": "包装项目案例",
    "mbti.phase4Text": "把项目呈现为具备清晰功能逻辑的社交产品，而不是单纯视觉实验。",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "马琛的 Lumi Galaxy 案例：一个包含 5 个像素风外星人桌面宠物、角色故事与互动网页世界的 AI 原生创意产品。",
    "lumi.kicker": "案例研究 · Lumi Galaxy",
    "lumi.title": "把角色宇宙塑造成 AI 原生产品闭环。",
    "lumi.lead": "Lumi Galaxy 是一个像素外星人桌面宠物网页世界，结合角色设计、世界观结构和 AI 辅助生产。",
    "lumi.overviewTitle": "产品视角",
    "lumi.overviewText": "Lumi Galaxy 是一个 AI 原生创意产品：5 个像素风格外星人桌面宠物，每个角色拥有独立世界观、性格设定、背景故事与互动方向，最终汇聚为可视化的“星球”网页。",
    "lumi.roleText": "我独立完成产品从 0 到 1 的定义与落地，包括产品形态定义、5 个外星人角色设定与世界观构建、交互体验设计、功能优先级排序、视觉方向、前端原型与后续迭代规划。",
    "lumi.decision1": "把项目定位为 AI 原生创意桌面宠物宇宙，而不是静态作品展示；每个角色都需要有明确性格、故事钩子和未来互动承诺。",
    "lumi.decision2": "使用 AI 工具批量生成 5 套角色背景故事、像素美术素材初稿与对话语料库，将原本需要美术与文案协作的内容生产环节压缩为单人可执行流程。",
    "lumi.decision3": "从产品构思、角色设定、技术选型到开发上线全流程独立完成，并持续围绕角色互动、页面表现和内容扩展方向迭代。",
    "lumi.executionTitle": "执行说明",
    "lumi.executionText": "该项目被设计为单人 0 到 1 工作流。AI 工具辅助创意发散、内容结构、网页实现与迭代，但产品方向始终保持角色、星球和世界观之间的视觉一致性。",
    "lumi.architectureTitle": "产品架构",
    "lumi.architectureText": "案例由视觉层、角色层和知识层共同构成。这个结构展示了它如何从作品集网页继续演化为带对话与持久记忆的 AI 伴侣产品。",
    "lumi.outcomeTitle": "结果",
    "lumi.outcomeText": "体现纯 AI 工具链单人完成创意产品从概念到上线的完整可行性，也体现创意产品 0 到 1 的头脑风暴能力、内容生产能力和网页落地能力。",
    "lumi.phase1Title": "定义世界与角色",
    "lumi.phase1Text": "建立像素外星人宇宙的人格系统、世界规则、视觉线索和互动承诺。",
    "lumi.phase2Title": "搭建角色内容系统",
    "lumi.phase2Text": "结构化角色背景、故事片段、视觉线索和对话语气，让每个外星人都有清晰可记忆的个性。",
    "lumi.phase3Title": "制作视觉原型",
    "lumi.phase3Text": "通过动效、星球隐喻和克制的玩味美术方向，把概念转化为网页体验。",
    "lumi.phase4Title": "上线与迭代",
    "lumi.phase4Text": "将项目包装为已发布的独立实验，并定义下一轮方向：对话、留存和更丰富的角色互动。",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "马琛的 AI Language Companion - Spanish Model 项目案例。",
    "workflow.kicker": "案例研究 · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "一个围绕西语对话模型展开的 AI 语伴项目，聚焦语言学习场景、陪练语气、本地化质量与模型评估闭环。",
    "workflow.overviewTitle": "产品视角",
    "workflow.overviewText": "这个案例页将用于补充西语 AI 语伴模型的完整项目细节：目标用户场景、陪练 Persona、对话质量标准、双语本地化评审与模型迭代方式。",
    "workflow.phase1Title": "定义学习场景",
    "workflow.phase1Text": "梳理日常会话、语法纠错、角色扮演、文化解释与信心建立等西语学习场景。",
    "workflow.phase2Title": "设计模型 Persona",
    "workflow.phase2Text": "定义语伴的语气、纠错方式、鼓励规则，以及它在导师、对话伙伴和文化解释者之间的边界。",
    "workflow.phase3Title": "建立评估闭环",
    "workflow.phase3Text": "围绕流利度、准确性、共情感、难度适配、文化细节和错误恢复能力建立评审标准。",
    "workflow.phase4Title": "补充项目细节",
    "workflow.phase4Text": "后续会继续加入模型样例、评估记录、Prompt 规则与本地化判断。",
    "workflow.architectureTitle": "模型工作流",
    "workflow.architectureText": "当前保留为模型工作流结构：场景输入、Persona 规则、回答生成、双语评审与迭代记录。",
    "workflow.executionTitle": "执行说明",
    "workflow.executionText": "这一页先作为西语模型项目壳保留，方便后续加入更具体的项目材料。",
    "workflow.outcomeTitle": "结果",
    "workflow.outcomeText": "一个预留好的 AI 语伴项目案例页，后续可承载模型样例、场景定义、评估标准与本地化决策。"
  }
};

Object.assign(translations.en, {
  "market.eyebrow": "Market range",
  "market.title": "Able to work across Europe, China, and Latin America.",
  "market.text": "Language fluency, cultural context, and localization judgment for products that need to travel well.",
  "projects.title": "Three product worlds, each given room to breathe."
});

Object.assign(translations.zh, {
  "market.eyebrow": "市场范围",
  "market.title": "能够覆盖欧洲、中国与拉丁美洲市场。",
  "market.text": "结合语言能力、文化语境与本地化判断，帮助产品跨市场成立。",
  "projects.title": "三个产品世界，各自拥有完整的展示空间。"
});

const capabilities = [
  {
    id: "01",
    enTitle: "AI product strategy",
    esTitle: "Estrategia de producto IA",
    zhTitle: "AI 产品策略",
    enText: "Problem framing, scenario design, prompt systems, and launch planning.",
    esText: "Definición de problema, diseño de escenarios, sistemas de prompt y planificación de lanzamiento.",
    zhText: "问题定义、场景设计、Prompt 系统与上线节奏。"
  },
  {
    id: "02",
    enTitle: "Localization and culture",
    esTitle: "Localización y cultura",
    zhTitle: "本地化与文化语境",
    enText: "Spanish, English, and Chinese product language with LATAM and EU sensitivity.",
    esText: "Lenguaje de producto en español, inglés y chino, con sensibilidad para LATAM y Europa.",
    zhText: "覆盖中文、英文、西语产品表达，并关注拉美与欧洲语境。"
  },
  {
    id: "03",
    enTitle: "User research",
    esTitle: "Investigación de usuarios",
    zhTitle: "用户研究",
    enText: "Interviews, persona synthesis, content analysis, and behavioral insight.",
    esText: "Entrevistas, síntesis de personas, análisis de contenido e insight de comportamiento.",
    zhText: "深度访谈、用户画像、内容分析与行为洞察。"
  },
  {
    id: "04",
    enTitle: "Interface storytelling",
    esTitle: "Narrativa de interfaz",
    zhTitle: "界面叙事",
    enText: "Visual hierarchy, case-study packaging, and product narrative design.",
    esText: "Jerarquía visual, presentación de casos y diseño narrativo de producto.",
    zhText: "视觉层级、案例包装与产品叙事设计。"
  }
];

function t(key, lang) {
  return translations[lang][key] || translations.en[key] || key;
}

function renderCapabilities(lang) {
  const root = document.querySelector("#capability-grid");
  if (!root) return;
  root.innerHTML = capabilities.map((item) => `
    <article class="capability-card">
      <span>${item.id}</span>
      <h3>${item[`${lang}Title`] || item.enTitle}</h3>
      <p>${item[`${lang}Text`] || item.enText}</p>
    </article>
  `).join("");
}

function setLanguage(lang) {
  document.documentElement.dataset.lang = lang;
  document.documentElement.lang = lang === "zh" ? "zh-CN" : lang;

  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.dataset.i18n, lang);
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((el) => {
    el.dataset.i18nAttr.split(",").forEach((pair) => {
      const [attr, key] = pair.split(":").map((value) => value.trim());
      if (attr && key) el.setAttribute(attr, t(key, lang));
    });
  });

  const titleEl = document.querySelector("title[data-i18n]");
  document.title = titleEl ? t(titleEl.dataset.i18n, lang) : t("meta.title", lang);
  renderCapabilities(lang);

  try {
    localStorage.setItem("site-lang", lang);
  } catch (error) {
    /* localStorage may be unavailable in some privacy modes */
  }
}

const savedLanguage = (() => {
  try {
    return localStorage.getItem("site-lang");
  } catch (error) {
    return null;
  }
})();

setLanguage(["en", "es", "zh"].includes(savedLanguage) ? savedLanguage : "en");

const toggle = document.querySelector(".lang-toggle");
if (toggle) {
  toggle.querySelectorAll("[data-lang-option]").forEach((button) => {
    button.addEventListener("click", () => {
      setLanguage(button.dataset.langOption);
    });
  });
}

(function initReveal() {
  const targets = document.querySelectorAll(".reveal");
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  if (reduced || !("IntersectionObserver" in window)) {
    targets.forEach((target) => target.classList.add("is-visible"));
    return;
  }

  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add("is-visible");
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.18, rootMargin: "0px 0px -10% 0px" });

  targets.forEach((target) => observer.observe(target));
})();
