const translations = {
  en: {
    "meta.title": "Ma Chen | AI Product Portfolio",
    "meta.description": "Ma Chen portfolio: AI product management, multilingual localization, agent workflows, and refined digital product case studies.",
    "nav.about": "About",
    "nav.projects": "Projects",
    "nav.experience": "Experience",
    "nav.process": "Process",
    "nav.contact": "Contact",
    "hero.eyebrow": "AI product manager · multilingual systems · crafted interfaces",
    "hero.titleA": "Designing AI products",
    "hero.titleB": "that feel local, useful, and alive.",
    "hero.lead": "I connect user research, language strategy, prompt systems, and front-end storytelling to turn complex AI workflows into polished product experiences.",
    "hero.ctaPrimary": "Explore projects",
    "hero.ctaSecondary": "Start a conversation",
    "hero.photoAlt": "Portrait of Ma Chen",
    "hero.signal": "Open to AI PM and product localization roles",
    "metrics.interviews": "user interviews",
    "metrics.samples": "UGC samples reviewed",
    "metrics.languages": "working languages",
    "about.eyebrow": "Profile",
    "about.title": "A product mind built between language, culture, and AI tooling.",
    "about.p1": "My background spans Spanish linguistics, digital humanities, AIGC globalization, content safety, and AI language companions.",
    "about.p2": "I like products where the interface is calm, the system is rigorous, and the user can feel that someone cared about the last ten percent.",
    "projects.eyebrow": "Selected work",
    "projects.title": "Two product worlds, each given room to breathe.",
    "projects.sub": "Full-screen chapters reveal the product story as you scroll: problem, interface logic, key features, and the delivery thinking behind each launch.",
    "project.detail": "View how it was made",
    "project.live": "Open live project",
    "project1.kicker": "Community product · MBTI discussion",
    "project1.title": "MBTI Discussion",
    "project1.lead": "A personality-type discussion experience designed around expressive identity, structured debate, and lightweight community participation.",
    "project1.f1": "Type-based exploration",
    "project1.f2": "Discussion-first information architecture",
    "project1.f3": "Identity cues and social entry points",
    "project2.kicker": "AI-native creative experiment · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "A pixel-alien desktop-pet universe with character lore, a visual planet, and an indie product loop powered by AI-assisted production.",
    "project2.f1": "Character system and worldbuilding",
    "project2.f2": "Character lore and story system",
    "project2.f3": "Playful web visualization",
    "project3.kicker": "AI language companion · Spanish model",
    "project3.title": "AI Language Companion",
    "project3.lead": "A Spanish language-companion model project focused on conversation quality, localization judgment, tutoring scenarios, and evaluation loops.",
    "project3.f1": "Spanish conversation model",
    "project3.f2": "Scenario and persona design",
    "project3.f3": "Localization QA loop",
    "experience.eyebrow": "Experience",
    "experience.title": "Professional and academic foundations behind the product work.",
    "experience.proLabel": "Professional",
    "experience.proTitle": "AI product, localization, and content safety",
    "experience.proText": "Work across AI language companions, AIGC globalization, user research, UGC evaluation, and multilingual product definition.",
    "experience.eduLabel": "Education",
    "experience.eduTitle": "Digital humanities and Spanish language background",
    "experience.eduText": "Training in Spanish linguistics, digital humanities, corpora, semantic web, visualization, and cross-cultural analysis.",
    "experience.toolLabel": "Tooling",
    "experience.toolTitle": "AI-assisted product execution",
    "experience.toolText": "Hands-on production with Codex, Claude Code, prompt workflows, structured knowledge bases, Figma, Notion, SQL, and data tools.",
    "process.eyebrow": "Method",
    "process.title": "How I shape product work from ambiguity to release.",
    "process.s1Title": "Frame the real problem",
    "process.s1Text": "Map users, scenarios, motivation, cultural context, and the emotional friction behind the request.",
    "process.s2Title": "Prototype the experience",
    "process.s2Text": "Translate insights into flows, prompts, content rules, and interface states that can be tested quickly.",
    "process.s3Title": "Build the operating system",
    "process.s3Text": "Define QA loops, localization logic, release phases, and measurable signals before scaling.",
    "contact.eyebrow": "Contact",
    "contact.title": "Let’s build AI products that feel carefully made.",
    "contact.resume": "Download resume",
    "case.back": "Back to portfolio",
    "case.live": "Open live project",
    "case.overview": "Overview",
    "case.phases": "Project phases",
    "case.architecture": "Product architecture",
    "case.execution": "Execution notes",
    "case.role": "My role",
    "case.decisions": "Key decisions",
    "case.outcome": "Outcome",
    "mbti.metaTitle": "MindPalace MBTI Discussion | Ma Chen",
    "mbti.metaDescription": "MindPalace / MBTI Discussion case study by Ma Chen: a multi-agent reflection table for emotion and relationship topics.",
    "mbti.kicker": "Case study · MBTI Discussion",
    "mbti.date": "2026.04 - Present",
    "mbti.title": "MindPalace: a multi-agent reflection table for MBTI discussion.",
    "mbti.lead": "Users enter an emotion or relationship topic, then four AI agents respond from NT, NF, SJ, and SP perspectives before debating with each other in a second round.",
    "mbti.overviewTitle": "Product lens",
    "mbti.overviewText": "MindPalace started from a very personal frustration: when I am emotionally confused, I usually look for empathy first. That helps, but it also means I keep hearing the kind of answer I already know how to receive. I wanted a small room where NT, NF, SJ, and SP could sit around the same question and make their differences visible.",
    "mbti.motiveLabel": "Starting point",
    "mbti.motiveTitle": "I kept hearing one kind of answer.",
    "mbti.motiveText": "As an NF user, I knew how easy it was to seek empathy and miss colder, faster, or more action-oriented perspectives.",
    "mbti.needLabel": "User need",
    "mbti.needTitle": "People want response styles, not just answers.",
    "mbti.needText": "Interviews showed that users care whether AI sounds understanding, practical, non-judgmental, or able to reveal a blind spot.",
    "mbti.validationLabel": "Early signal",
    "mbti.validationTitle": "3 of 4 testers felt clearer.",
    "mbti.validationText": "The strongest surprise was SP: direct, action-first responses helped users get unstuck.",
    "mbti.roleText": "I owned the product definition and delivery path: PRD, user flow, technical architecture, design rules, operations runbook, AI agent setup, front-end implementation, database connection, and Netlify deployment.",
    "mbti.decision1": "Defined the core scenario as a multi-perspective emotional reflection tool: users enter an emotion or relationship topic and receive independent responses from NT, NF, SJ, and SP thinking dimensions.",
    "mbti.decision2": "Designed a two-round discussion mechanism: the first round lets four agents respond independently, while the second round asks them to supplement and challenge each other based on the user's question and the first responses.",
    "mbti.decision3": "Used Claude Code / Cursor to turn product documents into a working web app with Next.js, TypeScript, Tailwind, API routes, Prisma, Supabase, DeepSeek API calls, and streamed output.",
    "mbti.executionTitle": "Execution notes",
    "mbti.executionText": "The build uses Claude Code as the main coding agent, DeepSeek API for model calls, Next.js 15 App Router, TypeScript, Tailwind 4, Prisma, Supabase for production data, SQLite locally, and GitHub to Netlify deployment. Claude Code handled component implementation, API routes, database schema, and deployment configuration; I owned the product judgment: requirement boundaries, interaction logic, agent prompts, and every iteration decision about whether the direction was right.",
    "mbti.architectureTitle": "Product architecture",
    "mbti.architectureText": "The product uses four MBTI cognitive dimensions instead of all 16 types, preserving the core difference in thinking styles while keeping the entry barrier low. Four agents answer independently in the first round, then debate with full context in the second round. The full timeline is shown at once, with customizable agent prompts, names, and colors, plus editable history titles and keyword search for reflection records.",
    "mbti.agentNt": "Rational analysis",
    "mbti.agentNf": "Emotional resonance",
    "mbti.agentSj": "Reality check",
    "mbti.agentSp": "Action instinct",
    "mbti.flow1": "User topic",
    "mbti.flow2": "Independent first round",
    "mbti.flow3": "Context-visible debate",
    "mbti.flow4": "Full timeline",
    "mbti.outcomeTitle": "Outcome",
    "mbti.outcomeText": "Three initial interviews confirmed the need for AI responses that feel less generic, less judgmental, and more perspective-rich. In a four-person product test, three users felt clearer or more certain after use, every user found at least one dimension relevant, and the SP perspective became a repeated surprise. The main improvement area is reducing the information density of the debate round.",
    "mbti.phase1Title": "Research the conversation model",
    "mbti.phase1Text": "Interviewed three people around emotional confusion, AI advice, and response preferences. The clearest signal was that people do not simply want an answer; they want a response style that matches or challenges their current state.",
    "mbti.phase2Title": "Define the product structure",
    "mbti.phase2Text": "Chose NT / NF / SJ / SP as the thinking-diversity framework instead of 16 MBTI types, because four dimensions are easier to understand while still creating visible contrast.",
    "mbti.phase3Title": "Design the interaction tone",
    "mbti.phase3Text": "Designed a two-stage response model: independent first-round answers to protect viewpoint integrity, followed by a context-aware debate round for contrast and challenge.",
    "mbti.phase4Title": "Package the case",
    "mbti.phase4Text": "Shipped the product as a usable web app with history, search, configurable agents, database persistence, and Netlify deployment, then validated it through four user tests.",
    "mbti.aiBuildText": "AI handled the engineering surface: components, API routes, database schema, deployment config.",
    "mbti.myJudgmentText": "I kept the product judgment: what should exist, where the boundary is, how each agent should sound, and when an iteration felt wrong.",
    "mbti.metricInterviews": "research interviews",
    "mbti.metricTests": "product tests",
    "mbti.metricClarity": "felt clearer or firmer",
    "mbti.metricSurprise": "most surprising view",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "Lumi Galaxy case study by Ma Chen: an AI-native creative product with five pixel-alien desktop pets, character stories, and an interactive web world.",
    "lumi.kicker": "Case study · Lumi Galaxy",
    "lumi.title": "A character universe shaped into an AI-native product loop.",
    "lumi.lead": "Lumi Galaxy is a playful web world for pixel-alien desktop pets, combining character design, lore structure, and AI-assisted production.",
    "lumi.overviewTitle": "Product lens",
    "lumi.overviewText": "Lumi Galaxy is an AI-native creative product built around five pixel-style alien desktop pets. Each character has its own world setting, personality, story material, and interaction direction, finally packaged into a visual Starball web experience.",
    "lumi.roleText": "I independently defined and built the product from 0 to 1, including the five alien characters, world setting, interaction experience, feature priority, visual direction, front-end prototype, and iteration plan.",
    "lumi.decision1": "Positioned Lumi Galaxy as an AI-native creative desktop-pet universe rather than a static showcase, giving each character its own personality, story hook, and interaction promise.",
    "lumi.decision2": "Used AI tools to accelerate character background writing, pixel-art asset drafts, dialogue tone, front-end prototyping, and visual iteration while keeping the creative direction coherent.",
    "lumi.decision3": "Compressed the usual art-plus-copy production loop into a solo executable workflow, so product concept, content production, and web launch could move together.",
    "lumi.executionTitle": "Execution notes",
    "lumi.executionText": "The build is framed as a solo 0-to-1 workflow. AI tools support ideation, content structuring, web implementation, and iteration, while the product direction keeps a coherent visual language across the planet, characters, and lore.",
    "lumi.architectureTitle": "Product architecture",
    "lumi.architectureText": "The case combines a visual layer, a character layer, and a knowledge layer. That structure shows how the project can evolve from a portfolio website into a richer AI companion product with dialogue and persistence.",
    "lumi.outcomeTitle": "Outcome",
    "lumi.outcomeText": "Demonstrated the feasibility of using a pure AI toolchain to move from creative concept to a launched product prototype. The project shows solo 0-to-1 product shaping, AI-assisted content production, and the ability to turn a playful idea into a polished web artifact.",
    "lumi.phase1Title": "World and character definition",
    "lumi.phase1Text": "Create the personality system, lore rules, visual cues, and interaction promise for the pixel-alien universe.",
    "lumi.phase2Title": "Character content system",
    "lumi.phase2Text": "Structure character backgrounds, story fragments, visual cues, and dialogue tone so each alien feels distinct and memorable.",
    "lumi.phase3Title": "Visual and desktop prototype",
    "lumi.phase3Text": "Turn the concept into a web experience and desktop companion package with motion states, menus, installation notes, and playful visual direction.",
    "lumi.phase4Title": "Launch and iteration",
    "lumi.phase4Text": "Package the project as a shipped indie experiment and define the next loop: memory, retention, and richer character interaction.",
    "lumi.navScope": "Project scope",
    "lumi.navProblem": "Problem",
    "lumi.navStrategy": "Product strategy",
    "lumi.navCharacters": "Character system",
    "lumi.navWorkflow": "AI workflow",
    "lumi.navRoadmap": "Roadmap",
    "lumi.metricCharacters": "pixel-alien companions",
    "lumi.metricStates": "desktop behavior states",
    "lumi.metricIntents": "dialogue intent categories",
    "lumi.metricLaunch": "live web case",
    "lumi.scopeTitle": "Project scope",
    "lumi.scopeText": "Because this is an independent project, the case is framed by scope rather than role: product definition, character system design, content production, prototype implementation, launch packaging, and the next iteration plan.",
    "lumi.problemTitle": "Problem and opportunity",
    "lumi.problemText": "Most desktop-pet products are visually cute but thin as systems: they can appear on screen, yet rarely carry a stable personality, world logic, dialogue style, or long-term interaction promise. Lumi Galaxy explores whether a small AI-native character universe can make desktop companionship feel more memorable and extensible.",
    "lumi.problemInsight1": "The core opportunity is not only \"make a cute pet\", but build a reusable character framework that can support different personalities, dialogue tones, visual states, and future memory.",
    "lumi.problemInsight2": "The product needed a narrow MVP: prove the universe, role differences, basic interaction, and launch packaging before expanding into deeper AI companion features.",
    "lumi.strategyTitle": "Product strategy",
    "lumi.strategyText": "The first version was positioned as a creative AI companion prototype, not a complete productivity tool. The priority was to validate whether the characters, world setting, and desktop/web experience could form a coherent product direction.",
    "lumi.strategyCard1Title": "Start with the universe",
    "lumi.strategyCard1Text": "Define the world, character set, visual identity, and interaction promise before adding heavy AI memory or personalization.",
    "lumi.strategyCard2Title": "Make roles distinct",
    "lumi.strategyCard2Text": "Each companion needs a different emotional rhythm, speaking style, and use scenario so the system does not feel like one generic assistant wearing five skins.",
    "lumi.strategyCard3Title": "Leave room to scale",
    "lumi.strategyCard3Text": "The data-driven character structure keeps the next steps open: more dialogue, persistent memory, richer desktop states, and themed character expansion.",
    "lumi.charactersTitle": "Character system",
    "lumi.charactersText": "The character layer is designed as a product system: each alien has an identity, personality, PAD emotion baseline, speaking style, visual assets, and dialogue direction.",
    "lumi.character1Title": "Curious explorer",
    "lumi.character1Text": "High curiosity and light energy; short sentences, sound effects, and a playful habit of reframing human life as alien-world logic.",
    "lumi.character2Title": "Gentle caretaker",
    "lumi.character2Text": "Slow, soft, and caring; built for low-pressure companionship, water reminders, and calm emotional support.",
    "lumi.character3Title": "Focused coding partner",
    "lumi.character3Text": "Precise and slightly dry; positioned as a calm companion for work sessions, coding focus, and quiet productivity.",
    "lumi.characterTag1": "Personality baseline",
    "lumi.characterTag2": "PAD emotion parameters",
    "lumi.characterTag3": "Dialogue intent categories",
    "lumi.characterTag4": "Visual state assets",
    "lumi.characterTag5": "Future memory hooks",
    "lumi.workflowTitle": "AI production workflow",
    "lumi.workflowText": "AI tools were used as production accelerators, while the product decisions stayed human-led: what the product should be, how each character should differ, what to keep in the MVP, and when the output no longer matched the world direction.",
    "lumi.workflowStep1": "Concept and positioning",
    "lumi.workflowStep2": "Character writing and visual drafts",
    "lumi.workflowStep3": "Dialogue data and frontend prototype",
    "lumi.workflowStep4": "Manual direction, pruning, and launch",
    "lumi.aiBuildText": "AI helped produce character background drafts, pixel-art directions, dialogue variants, page implementation, and iteration options.",
    "lumi.myJudgmentText": "The product judgment stayed in the selection layer: choosing the product boundary, unifying tone, rejecting inconsistent assets, and shaping the roadmap.",
    "lumi.arch1Title": "Web planet and desktop surface",
    "lumi.arch1Text": "A public web case and a desktop companion shell make the product visible, shareable, and easy to inspect.",
    "lumi.arch2Title": "Configurable companion data",
    "lumi.arch2Text": "Character profiles, emotional baselines, assets, and dialogue rules are separated from the interface so the universe can expand.",
    "lumi.arch3Title": "Dialogue, menus, states, and mini-games",
    "lumi.arch3Text": "The experience includes basic interaction hooks that can later connect to memory, personalization, and richer AI behavior.",
    "lumi.roadmapTitle": "Iteration roadmap",
    "lumi.roadmapText": "The roadmap separates what has already been validated from what should come next, so the case reads like an evolving product rather than a one-time visual experiment.",
    "lumi.roadmap1Title": "World, role, and website",
    "lumi.roadmap1Text": "Define the universe, ship the visual web page, and make the project externally readable.",
    "lumi.roadmap2Title": "Desktop pet and interaction shell",
    "lumi.roadmap2Text": "Support desktop presence, menus, state changes, installation notes, and basic playful interactions.",
    "lumi.roadmap3Title": "Dialogue and emotional response",
    "lumi.roadmap3Text": "Expand intent recognition, character-specific replies, PAD emotion changes, and small interaction loops.",
    "lumi.roadmap4Title": "Memory and character growth",
    "lumi.roadmap4Text": "Add user preferences, long-term memory, relationship progression, and richer companion behavior.",
    "lumi.outcomeTag1": "Published web case",
    "lumi.outcomeTag2": "Desktop installation guide",
    "lumi.outcomeTag3": "Character data model",
    "lumi.outcomeTag4": "Dialogue dataset draft",
    "lumi.outcomeTag5": "Iteration roadmap",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "AI Language Companion - Spanish Model case study by Ma Chen.",
    "workflow.kicker": "Case study · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "A Spanish conversation-model project focused on language-learning scenarios, tutoring tone, localization quality, and model evaluation loops.",
    "workflow.overviewTitle": "Product lens",
    "workflow.overviewText": "This case will document how a Spanish language-companion model is shaped through target user scenarios, tutoring persona definition, conversation quality standards, and bilingual localization review.",
    "workflow.roleText": "I will add the detailed work scope, product responsibilities, model evaluation ownership, and localization collaboration notes here.",
    "workflow.decision1": "Define the target Spanish-learning scenarios and conversation-quality standards.",
    "workflow.decision2": "Shape the companion persona, correction style, and bilingual review process.",
    "workflow.decision3": "Build an evaluation loop for fluency, accuracy, empathy, cultural nuance, and level fit.",
    "workflow.phase1Title": "Define learning scenarios",
    "workflow.phase1Text": "Map practice contexts such as daily conversation, grammar correction, role-play, cultural explanation, and confidence building for Spanish learners.",
    "workflow.phase2Title": "Shape the model persona",
    "workflow.phase2Text": "Define the companion's tone, correction style, encouragement rules, and boundaries between tutor, conversation partner, and cultural explainer.",
    "workflow.phase3Title": "Build evaluation loops",
    "workflow.phase3Text": "Create review criteria for fluency, accuracy, empathy, level fit, cultural nuance, and recovery from user mistakes.",
    "workflow.phase4Title": "Package the case details",
    "workflow.phase4Text": "The detailed product artifacts, samples, and evaluation notes will be added in the next iteration.",
    "workflow.architectureTitle": "Model workflow",
    "workflow.architectureText": "The current structure is reserved for the model workflow: scenario input, persona rules, response generation, bilingual review, and iteration notes.",
    "workflow.executionTitle": "Execution notes",
    "workflow.executionText": "This page is intentionally kept as a project shell for now so more concrete Spanish model details can be added cleanly later.",
    "workflow.outcomeTitle": "Outcome",
    "workflow.outcomeText": "A reserved AI language-companion case page that can later hold model samples, scenario definitions, evaluation criteria, and localization decisions."
  },
  es: {
    "meta.title": "Ma Chen | Portfolio de Producto IA",
    "meta.description": "Portfolio de Ma Chen: product management de IA, localización multilingüe, workflows con agentes y casos de producto digital.",
    "nav.about": "Perfil",
    "nav.projects": "Proyectos",
    "nav.experience": "Experiencia",
    "nav.process": "Método",
    "nav.contact": "Contacto",
    "hero.eyebrow": "Product manager IA · sistemas multilingües · interfaces cuidadas",
    "hero.titleA": "Diseño productos IA",
    "hero.titleB": "útiles, locales y memorables.",
    "hero.lead": "Conecto investigación de usuarios, estrategia lingüística, sistemas de prompt y narrativa visual para convertir workflows complejos de IA en experiencias de producto pulidas.",
    "hero.ctaPrimary": "Ver proyectos",
    "hero.ctaSecondary": "Hablemos",
    "hero.photoAlt": "Retrato de Ma Chen",
    "hero.signal": "Abierta a roles de AI PM y localización de producto",
    "metrics.interviews": "entrevistas a usuarios",
    "metrics.samples": "muestras UGC evaluadas",
    "metrics.languages": "idiomas de trabajo",
    "about.eyebrow": "Perfil",
    "about.title": "Una mirada de producto construida entre lenguaje, cultura y herramientas de IA.",
    "about.p1": "Mi trayectoria combina lingüística hispánica, humanidades digitales, globalización AIGC, seguridad de contenido y productos de compañeros lingüísticos con IA.",
    "about.p2": "Me interesan los productos con una interfaz serena, un sistema riguroso y un nivel de detalle que haga sentir al usuario que alguien cuidó el último diez por ciento.",
    "market.eyebrow": "Alcance de mercado",
    "market.title": "Capacidad para trabajar en Europa, China y América Latina.",
    "market.text": "Fluidez lingüística, contexto cultural y criterio de localización para productos que necesitan viajar bien entre mercados.",
    "projects.eyebrow": "Trabajo seleccionado",
    "projects.title": "Tres mundos de producto, cada uno con espacio propio.",
    "projects.sub": "Capítulos a pantalla completa muestran la historia de cada proyecto: problema, lógica de interfaz, funcionalidades y decisiones de entrega.",
    "project.detail": "Ver cómo se construyó",
    "project.live": "Abrir proyecto online",
    "project1.kicker": "Producto comunitario · MBTI discussion",
    "project1.title": "MBTI Discussion",
    "project1.lead": "Una experiencia de discusión sobre tipos de personalidad diseñada alrededor de identidad, debate estructurado y participación ligera.",
    "project1.f1": "Exploración por tipo",
    "project1.f2": "Arquitectura centrada en conversación",
    "project1.f3": "Señales de identidad y entrada social",
    "project2.kicker": "Experimento creativo AI-native · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "Un universo de mascotas alienígenas pixel art con lore de personajes, planeta visual y un ciclo indie producido con apoyo de IA.",
    "project2.f1": "Sistema de personajes y worldbuilding",
    "project2.f2": "Sistema de personajes y relatos",
    "project2.f3": "Visualización web lúdica",
    "project3.kicker": "Compañero lingüístico IA · modelo español",
    "project3.title": "AI Language Companion",
    "project3.lead": "Un proyecto de modelo conversacional en español centrado en calidad de diálogo, criterio de localización, escenarios de aprendizaje y ciclos de evaluación.",
    "project3.f1": "Modelo conversacional español",
    "project3.f2": "Diseño de escenarios y persona",
    "project3.f3": "QA de localización",
    "experience.eyebrow": "Experiencia",
    "experience.title": "Base profesional y académica detrás del trabajo de producto.",
    "experience.proLabel": "Profesional",
    "experience.proTitle": "Producto IA, localización y seguridad de contenido",
    "experience.proText": "Trabajo en AI language companions, globalización AIGC, investigación de usuarios, evaluación UGC y definición de producto multilingüe.",
    "experience.eduLabel": "Educación",
    "experience.eduTitle": "Humanidades digitales y formación en español",
    "experience.eduText": "Formación en lingüística hispánica, humanidades digitales, corpus, web semántica, visualización y análisis intercultural.",
    "experience.toolLabel": "Herramientas",
    "experience.toolTitle": "Ejecución de producto asistida por IA",
    "experience.toolText": "Producción práctica con Codex, Claude Code, workflows de prompts, bases de conocimiento estructuradas, Figma, Notion, SQL y herramientas de datos.",
    "process.eyebrow": "Método",
    "process.title": "Cómo llevo una necesidad ambigua hasta un producto publicable.",
    "process.s1Title": "Definir el problema real",
    "process.s1Text": "Mapeo usuarios, escenarios, motivación, contexto cultural y la fricción emocional detrás de la necesidad.",
    "process.s2Title": "Prototipar la experiencia",
    "process.s2Text": "Transformo insights en flujos, prompts, reglas de contenido y estados de interfaz que se pueden probar rápido.",
    "process.s3Title": "Construir el sistema de entrega",
    "process.s3Text": "Defino ciclos de QA, lógica de localización, fases de lanzamiento y señales medibles antes de escalar.",
    "contact.eyebrow": "Contacto",
    "contact.title": "Construyamos productos IA que se sientan cuidadosamente hechos.",
    "contact.resume": "Descargar CV",
    "case.back": "Volver al portfolio",
    "case.live": "Abrir proyecto online",
    "case.overview": "Resumen",
    "case.phases": "Fases del proyecto",
    "case.architecture": "Arquitectura de producto",
    "case.execution": "Ejecución",
    "case.role": "Mi rol",
    "case.decisions": "Decisiones clave",
    "case.outcome": "Resultado",
    "mbti.metaTitle": "MindPalace MBTI Discussion | Ma Chen",
    "mbti.metaDescription": "Caso de MindPalace / MBTI Discussion de Ma Chen: una mesa de reflexión multiagente para temas emocionales y relacionales.",
    "mbti.kicker": "Caso · MBTI Discussion",
    "mbti.date": "2026.04 - actualidad",
    "mbti.title": "MindPalace: una mesa de reflexión multiagente para discusión MBTI.",
    "mbti.lead": "El usuario introduce un tema emocional o relacional; cuatro agentes IA responden desde perspectivas NT, NF, SJ y SP, y luego debaten entre sí en una segunda ronda.",
    "mbti.overviewTitle": "Mirada de producto",
    "mbti.overviewText": "MindPalace nació de una frustración muy personal: cuando estoy confundida emocionalmente, busco empatía primero. Eso ayuda, pero también hace que escuche siempre el tipo de respuesta que ya sé recibir. Quería una pequeña sala donde NT, NF, SJ y SP pudieran mirar la misma pregunta desde lugares distintos.",
    "mbti.motiveLabel": "Punto de partida",
    "mbti.motiveTitle": "Escuchaba siempre un tipo de respuesta.",
    "mbti.motiveText": "Como usuaria NF, sabía lo fácil que era buscar empatía y perder perspectivas más frías, rápidas o orientadas a acción.",
    "mbti.needLabel": "Necesidad",
    "mbti.needTitle": "La gente quiere estilos de respuesta, no solo respuestas.",
    "mbti.needText": "Las entrevistas mostraron que importa si la IA suena comprensiva, práctica, no juzgadora o capaz de mostrar un punto ciego.",
    "mbti.validationLabel": "Señal inicial",
    "mbti.validationTitle": "3 de 4 testers terminaron con más claridad.",
    "mbti.validationText": "La sorpresa más fuerte fue SP: respuestas directas y orientadas a acción ayudaron a salir del bloqueo.",
    "mbti.roleText": "Me encargué de la definición de producto y la ruta de entrega: PRD, flujo de usuario, arquitectura técnica, reglas de diseño, runbook operativo, configuración de agentes IA, implementación front-end, conexión de base de datos y despliegue en Netlify.",
    "mbti.decision1": "Definí el escenario principal como una herramienta de reflexión emocional multiperspectiva: el usuario introduce un tema y recibe respuestas independientes desde cuatro dimensiones de pensamiento.",
    "mbti.decision2": "Diseñé un mecanismo de discusión en dos rondas: primero cuatro agentes responden de forma independiente; después se complementan y refutan entre sí a partir de la pregunta y las respuestas iniciales.",
    "mbti.decision3": "Usé Claude Code / Cursor para convertir documentación de producto en una app funcional con Next.js, TypeScript, Tailwind, API routes, Prisma, Supabase, llamadas a DeepSeek API y salida en streaming.",
    "mbti.executionTitle": "Ejecución",
    "mbti.executionText": "El proyecto usa Claude Code como agente principal de programación, DeepSeek API para inferencia, Next.js 15 App Router, TypeScript, Tailwind 4, Prisma, Supabase en producción, SQLite en local y despliegue GitHub a Netlify. Claude Code ejecutó componentes, API routes, schema y configuración; yo tomé las decisiones de producto, límites, lógica de interacción, prompts de agentes e iteración.",
    "mbti.architectureTitle": "Arquitectura de producto",
    "mbti.architectureText": "El producto usa cuatro dimensiones cognitivas MBTI en lugar de 16 tipos, reduciendo la barrera de entrada sin perder contraste. Cuatro agentes responden de forma independiente en la primera ronda y luego debaten con contexto completo. La línea temporal se muestra completa, con prompts, nombres y colores configurables, además de historial editable y búsqueda por palabras clave.",
    "mbti.agentNt": "Análisis racional",
    "mbti.agentNf": "Resonancia emocional",
    "mbti.agentSj": "Chequeo de realidad",
    "mbti.agentSp": "Instinto de acción",
    "mbti.flow1": "Tema del usuario",
    "mbti.flow2": "Primera ronda independiente",
    "mbti.flow3": "Debate con contexto",
    "mbti.flow4": "Timeline completo",
    "mbti.outcomeTitle": "Resultado",
    "mbti.outcomeText": "Tres entrevistas iniciales confirmaron la necesidad de respuestas IA menos genéricas, menos juzgadoras y con más perspectiva. En una prueba con cuatro usuarios, tres terminaron con más claridad o seguridad; todos encontraron al menos una dimensión relevante, y la perspectiva SP apareció como sorpresa recurrente. El principal punto a mejorar es bajar la densidad informativa de la ronda de debate.",
    "mbti.phase1Title": "Investigar el modelo conversacional",
    "mbti.phase1Text": "Entrevisté a tres personas sobre confusión emocional, consejos de IA y preferencias de respuesta. La señal central fue que no buscan solo una respuesta, sino un estilo que acompañe o cuestione su estado actual.",
    "mbti.phase2Title": "Definir la estructura del producto",
    "mbti.phase2Text": "Elegí NT / NF / SJ / SP como marco de diversidad cognitiva en lugar de 16 tipos MBTI, porque cuatro dimensiones son más intuitivas y mantienen contraste claro.",
    "mbti.phase3Title": "Diseñar el tono de interacción",
    "mbti.phase3Text": "Diseñé un modelo en dos etapas: respuestas independientes en primera ronda para proteger cada punto de vista, y debate con contexto completo en segunda ronda.",
    "mbti.phase4Title": "Empaquetar el caso",
    "mbti.phase4Text": "Lo lancé como una web usable con historial, búsqueda, agentes configurables, persistencia de datos y despliegue en Netlify, y luego lo validé con cuatro pruebas de usuario.",
    "mbti.aiBuildText": "La IA cubrió la superficie técnica: componentes, API routes, schema de base de datos y configuración de despliegue.",
    "mbti.myJudgmentText": "Yo mantuve el criterio de producto: qué debía existir, dónde estaban los límites, cómo debía sonar cada agente y cuándo una iteración se sentía equivocada.",
    "mbti.metricInterviews": "entrevistas",
    "mbti.metricTests": "tests de producto",
    "mbti.metricClarity": "con más claridad o firmeza",
    "mbti.metricSurprise": "perspectiva más sorprendente",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "Caso de Lumi Galaxy de Ma Chen: producto creativo AI-native con cinco mascotas alienígenas pixel art, historias de personajes y mundo web interactivo.",
    "lumi.kicker": "Caso · Lumi Galaxy",
    "lumi.title": "Un universo de personajes convertido en un ciclo de producto AI-native.",
    "lumi.lead": "Lumi Galaxy es un mundo web de mascotas alienígenas pixel art que combina diseño de personajes, estructura de lore y producción asistida por IA.",
    "lumi.overviewTitle": "Mirada de producto",
    "lumi.overviewText": "Lumi Galaxy es un producto creativo AI-native alrededor de cinco mascotas alienígenas pixel art. Cada personaje tiene mundo, personalidad, historia e interacción propia, empaquetado en una experiencia web visual Starball.",
    "lumi.roleText": "Definí y construí de forma independiente el producto de 0 a 1: cinco personajes alienígenas, mundo narrativo, experiencia de interacción, prioridades funcionales, dirección visual, prototipo front-end y plan de iteración.",
    "lumi.decision1": "Posicioné Lumi Galaxy como un universo creativo de mascotas de escritorio AI-native, no como una vitrina estática, para que cada personaje tuviera personalidad, gancho narrativo y promesa de interacción.",
    "lumi.decision2": "Usé herramientas IA para acelerar historias de personajes, borradores visuales pixel art, tono de diálogo, prototipado front-end e iteración visual manteniendo una dirección creativa coherente.",
    "lumi.decision3": "Comprimí el ciclo habitual de arte y copy en un flujo ejecutable por una sola persona, conectando concepto de producto, producción de contenido y lanzamiento web.",
    "lumi.executionTitle": "Ejecución",
    "lumi.executionText": "El proyecto está planteado como un flujo solo 0 a 1. Las herramientas de IA apoyan ideación, estructura de contenido, implementación web e iteración, mientras la dirección mantiene coherencia visual entre planeta, personajes y lore.",
    "lumi.architectureTitle": "Arquitectura de producto",
    "lumi.architectureText": "El caso combina una capa visual, una capa de personajes y una capa de conocimiento. Esa estructura muestra cómo puede evolucionar de portfolio web a producto de compañero IA con diálogo y persistencia.",
    "lumi.outcomeTitle": "Resultado",
    "lumi.outcomeText": "Demostró la viabilidad de usar una cadena de herramientas IA para pasar de concepto creativo a prototipo publicado. El proyecto muestra definición 0 a 1, producción de contenido asistida por IA y capacidad de convertir una idea lúdica en una pieza web pulida.",
    "lumi.phase1Title": "Definir mundo y personajes",
    "lumi.phase1Text": "Crear el sistema de personalidad, reglas de lore, señales visuales y promesa interactiva del universo pixel alien.",
    "lumi.phase2Title": "Sistema de contenido de personajes",
    "lumi.phase2Text": "Estructurar fondos de personaje, fragmentos de historia, señales visuales y tono de diálogo para que cada alien tenga una identidad clara.",
    "lumi.phase3Title": "Prototipo visual de producto",
    "lumi.phase3Text": "Convertir el concepto en una experiencia web con movimiento, metáforas planetarias y una dirección artística controlada.",
    "lumi.phase4Title": "Lanzamiento e iteración",
    "lumi.phase4Text": "Presentar el proyecto como experimento indie publicado y definir el siguiente ciclo: diálogo, retención e interacción más rica.",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "Caso de AI Language Companion - Spanish Model de Ma Chen.",
    "workflow.kicker": "Caso · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "Un proyecto de modelo conversacional en español centrado en escenarios de aprendizaje, tono tutorial, calidad de localización y ciclos de evaluación.",
    "workflow.overviewTitle": "Mirada de producto",
    "workflow.overviewText": "Este caso documentará cómo se define un modelo de compañero lingüístico en español mediante escenarios de usuario, persona tutorial, estándares de conversación y revisión bilingüe.",
    "workflow.roleText": "Aquí añadiré el alcance concreto del trabajo, responsabilidades de producto, ownership de evaluación del modelo y colaboración de localización.",
    "workflow.decision1": "Definir los escenarios objetivo de aprendizaje de español y los estándares de calidad conversacional.",
    "workflow.decision2": "Diseñar la persona del compañero, el estilo de corrección y el proceso de revisión bilingüe.",
    "workflow.decision3": "Construir un ciclo de evaluación para fluidez, precisión, empatía, matiz cultural y adaptación al nivel del usuario.",
    "workflow.phase1Title": "Definir escenarios de aprendizaje",
    "workflow.phase1Text": "Mapear prácticas como conversación diaria, corrección gramatical, role-play, explicación cultural y construcción de confianza.",
    "workflow.phase2Title": "Diseñar la persona del modelo",
    "workflow.phase2Text": "Definir tono, estilo de corrección, reglas de ánimo y límites entre tutor, compañero de conversación y explicador cultural.",
    "workflow.phase3Title": "Construir ciclos de evaluación",
    "workflow.phase3Text": "Crear criterios de revisión sobre fluidez, precisión, empatía, nivel del usuario, matiz cultural y recuperación ante errores.",
    "workflow.phase4Title": "Completar el caso",
    "workflow.phase4Text": "Los artefactos, muestras y notas de evaluación se añadirán en una siguiente iteración.",
    "workflow.architectureTitle": "Flujo del modelo",
    "workflow.architectureText": "La estructura queda reservada para el flujo del modelo: escenario, reglas de persona, generación, revisión bilingüe e iteración.",
    "workflow.executionTitle": "Ejecución",
    "workflow.executionText": "Esta página se mantiene como base de caso para añadir después detalles concretos del modelo español.",
    "workflow.outcomeTitle": "Resultado",
    "workflow.outcomeText": "Una página de caso reservada para incorporar muestras del modelo, escenarios, criterios de evaluación y decisiones de localización."
  },
  zh: {
    "meta.title": "马琛 | AI 产品作品集",
    "meta.description": "马琛的个人作品集：AI 产品管理、多语言本地化、Agent 工作流与高质感数字产品案例。",
    "nav.about": "关于",
    "nav.projects": "项目",
    "nav.experience": "经历",
    "nav.process": "方法",
    "nav.contact": "联系",
    "hero.eyebrow": "AI 产品经理 · 多语言系统 · 精致界面体验",
    "hero.titleA": "设计真正有用的",
    "hero.titleB": "AI 产品体验。",
    "hero.lead": "我把用户研究、语言策略、Prompt 系统与前端叙事连接起来，把复杂的 AI 工作流转化为清晰、专业、有温度的产品体验。",
    "hero.ctaPrimary": "浏览项目",
    "hero.ctaSecondary": "联系我",
    "hero.photoAlt": "马琛的个人照片",
    "hero.signal": "关注 AI PM 与产品本地化机会",
    "metrics.interviews": "用户深访",
    "metrics.samples": "UGC 样本评估",
    "metrics.languages": "工作语言",
    "about.eyebrow": "个人简介",
    "about.title": "一个建立在语言、文化与 AI 工具链之间的产品视角。",
    "about.p1": "我的经历横跨西班牙语语言学、数字人文、AIGC 出海、内容安全与 AI 语伴产品。",
    "about.p2": "我喜欢界面克制、系统严谨、并且能让用户感受到最后 10% 细节也被认真打磨过的产品。",
    "projects.eyebrow": "精选项目",
    "projects.title": "两个产品世界，各自拥有完整的展示空间。",
    "projects.sub": "页面会随着滚动展开项目故事：问题、界面逻辑、核心功能，以及每次发布背后的产品判断。",
    "project.detail": "查看项目如何完成",
    "project.live": "打开线上项目",
    "project1.kicker": "社区产品 · MBTI 讨论",
    "project1.title": "MBTI Discussion",
    "project1.lead": "一个围绕人格类型、身份表达、结构化讨论和轻量社区参与设计的讨论型产品体验。",
    "project1.f1": "基于类型的探索路径",
    "project1.f2": "讨论优先的信息架构",
    "project1.f3": "身份线索与社交入口",
    "project2.kicker": "AI 原生创意实验 · Lumi Galaxy",
    "project2.title": "Lumi Galaxy",
    "project2.lead": "一个像素外星人桌面宠物宇宙，包含角色设定、视觉星球与 AI 辅助完成的独立产品闭环。",
    "project2.f1": "角色系统与世界观",
    "project2.f2": "角色故事与内容系统",
    "project2.f3": "带有玩味的网页可视化",
    "project3.kicker": "AI 语伴产品 · 西语模型",
    "project3.title": "AI Language Companion",
    "project3.lead": "一个围绕西语对话模型展开的 AI 语伴项目，关注学习场景、陪练语气、本地化质量与模型评估闭环。",
    "project3.f1": "西语对话模型",
    "project3.f2": "场景与 Persona 设计",
    "project3.f3": "本地化质检闭环",
    "experience.eyebrow": "经历",
    "experience.title": "支撑产品工作的职业与教育背景。",
    "experience.proLabel": "职业经验",
    "experience.proTitle": "AI 产品、本地化与内容安全",
    "experience.proText": "覆盖 AI 语伴、AIGC 出海、用户研究、UGC 评估与多语言产品定义。",
    "experience.eduLabel": "教育背景",
    "experience.eduTitle": "数字人文与西班牙语背景",
    "experience.eduText": "接受过西班牙语语言学、数字人文、语料库、语义网、可视化与跨文化分析训练。",
    "experience.toolLabel": "工具链",
    "experience.toolTitle": "AI 辅助产品执行",
    "experience.toolText": "实际使用 Codex、Claude Code、Prompt 工作流、结构化知识库、Figma、Notion、SQL 与数据工具完成项目。",
    "process.eyebrow": "方法",
    "process.title": "我如何把模糊需求推进到可发布的产品。",
    "process.s1Title": "定义真实问题",
    "process.s1Text": "梳理用户、场景、动机、文化语境，以及需求背后的情绪摩擦。",
    "process.s2Title": "快速原型体验",
    "process.s2Text": "把洞察转化为流程、Prompt、内容规则与可快速验证的界面状态。",
    "process.s3Title": "建立交付系统",
    "process.s3Text": "在规模化之前定义质检闭环、本地化逻辑、上线阶段与可衡量信号。",
    "contact.eyebrow": "联系",
    "contact.title": "一起做真正被认真打磨过的 AI 产品。",
    "contact.resume": "下载简历",
    "case.back": "返回作品集",
    "case.live": "打开线上项目",
    "case.overview": "项目概览",
    "case.phases": "项目阶段",
    "case.architecture": "产品架构",
    "case.execution": "执行说明",
    "case.role": "我的职责",
    "case.decisions": "关键决策",
    "case.outcome": "结果",
    "mbti.metaTitle": "MindPalace MBTI 讨论会 | Ma Chen",
    "mbti.metaDescription": "马琛的 MindPalace / MBTI 讨论会案例：围绕情感与关系话题的多 Agent 反思圆桌 Web 应用。",
    "mbti.kicker": "案例研究 · MBTI Discussion",
    "mbti.date": "2026.04 - 至今",
    "mbti.title": "MindPalace：一个多 Agent 情感反思圆桌。",
    "mbti.lead": "用户输入一个情感或关系类话题后，系统调用 NT / NF / SJ / SP 四个不同思维维度的 AI Agent，完成首轮独立回应与第二轮互相辩论。",
    "mbti.overviewTitle": "产品视角",
    "mbti.overviewText": "MindPalace 其实是从我自己的情感困惑里长出来的。我是 NF，遇到关系问题时第一反应是找人倾诉、寻求共情，这当然有用，但也会让我一直听到自己熟悉的那种答案。我想做一个小房间，让 NT、NF、SJ、SP 坐在同一个问题旁边，把他们的差异直接摆出来。",
    "mbti.motiveLabel": "起点",
    "mbti.motiveTitle": "我总是在听同一种答案。",
    "mbti.motiveText": "作为 NF，我很容易先找共情，但也因此错过更理性、更直接、或者更行动导向的视角。",
    "mbti.needLabel": "需求",
    "mbti.needTitle": "用户要的不只是答案，而是回应方式。",
    "mbti.needText": "访谈里最明显的信号是：大家会在意 AI 是理解我、给建议、不评判，还是能指出我没想到的盲区。",
    "mbti.validationLabel": "早期验证",
    "mbti.validationTitle": "4 个体验者里 3 个更清晰。",
    "mbti.validationText": "最意外的是 SP 视角：直接、行动优先的回答，反而最容易把人从纠结里拽出来。",
    "mbti.roleText": "我负责从产品定义到上线的完整链路，包括 PRD、用户流程、技术架构、设计规范、运维 Runbook、AI Agent 编排、前后端开发、数据库接入与 Netlify 部署。",
    "mbti.decision1": "从个人真实需求出发，将核心场景定义为“多视角情感反思工具”：用户输入情绪或关系话题后，由 NT / NF / SJ / SP 四类人格 Agent 分别回应。",
    "mbti.decision2": "设计“两阶段讨论机制”：首轮 4 个 Agent 独立回应，第二轮基于用户问题与全员首轮发言进行互相补充和反驳，保证上下文完整性与多视角表达质量。",
    "mbti.decision3": "使用 Claude Code / Cursor 等 AI 编程工具辅助完成 Next.js、TypeScript、Tailwind、API Route、Prisma、Supabase、DeepSeek API 调用与 SSE 流式输出等功能开发。",
    "mbti.executionTitle": "执行说明",
    "mbti.executionText": "技术上使用 Claude Code 作为主力编程 Agent、DeepSeek API 作为推理调用，前端为 Next.js 15 App Router、TypeScript、Tailwind 4，数据层为 Prisma + Supabase（生产）/ SQLite（本地），通过 GitHub 到 Netlify 部署，并用 Agent seed 脚本初始化人格配置。Claude Code 负责组件、API、数据库 schema 和部署配置，我负责需求边界、交互逻辑、人格提示词设计，以及每次迭代“方向是否正确”的产品判断。",
    "mbti.architectureTitle": "产品架构",
    "mbti.architectureText": "产品用 NT / NF / SJ / SP 四个认知维度作为思维多样性的代理框架，而不是 16 型 MBTI，以降低认知门槛并保留视角碰撞。核心体验是四维度 Agent 并行首轮回应，再进行一轮互相辩论，并一次性展示完整时间线。首轮彼此不可见，辩论轮全员上下文可见；同时支持 Agent 提示词、名称、颜色自定义，以及历史话题标题编辑和关键字检索。",
    "mbti.agentNt": "理性分析",
    "mbti.agentNf": "情绪共鸣",
    "mbti.agentSj": "现实校准",
    "mbti.agentSp": "行动直觉",
    "mbti.flow1": "用户话题",
    "mbti.flow2": "首轮独立回应",
    "mbti.flow3": "带上下文辩论",
    "mbti.flow4": "完整时间线",
    "mbti.outcomeTitle": "结果",
    "mbti.outcomeText": "需求调研阶段访谈了 3 人，验证了用户对“能听懂我但不评判”“给切实建议”“看到自己想不到角度”的需求。产品体验验证中，4 人里有 3 人用完后表示更清晰或更坚定；所有人至少有一个维度说到点上；SP 视角成为普遍意外惊喜。主要待改进点是辩论轮信息密度偏高，需要进一步降低阅读负担。",
    "mbti.phase1Title": "研究讨论模型",
    "mbti.phase1Text": "从自身痛点和身边人的倾诉习惯出发，访谈 3 位用户，确认大家在情感困惑时并不只是要答案，而是需要不同回应方式：共情、建议、理性拆解或行动视角。",
    "mbti.phase2Title": "定义产品结构",
    "mbti.phase2Text": "选择 NT / NF / SJ / SP 四个维度，而不是 16 型人格。这样保留思维差异碰撞，又能让不了解 MBTI 的用户快速理解。",
    "mbti.phase3Title": "设计交互语气",
    "mbti.phase3Text": "设计两阶段机制：首轮 4 个 Agent 独立回应，保证观点独立；第二轮基于全员上下文互相补充和反驳，形成真正的视角碰撞。",
    "mbti.phase4Title": "包装项目案例",
    "mbti.phase4Text": "完成从产品定义、Agent 编排、前后端开发、数据库接入到 Netlify 部署的上线链路，并通过 4 人使用测试验证清晰度和复用意愿。",
    "mbti.aiBuildText": "AI 负责工程表层：组件、API 路由、数据库 schema、部署配置。",
    "mbti.myJudgmentText": "我负责产品判断：什么该做、边界在哪里、每个 Agent 应该怎么说话，以及哪次迭代方向不对。",
    "mbti.metricInterviews": "需求访谈",
    "mbti.metricTests": "产品体验测试",
    "mbti.metricClarity": "更清晰或更坚定",
    "mbti.metricSurprise": "最意外的视角",
    "lumi.metaTitle": "Lumi Galaxy | Ma Chen",
    "lumi.metaDescription": "马琛的 Lumi Galaxy 案例：一个包含 5 个像素风外星人桌面宠物、角色故事与互动网页世界的 AI 原生创意产品。",
    "lumi.kicker": "案例研究 · Lumi Galaxy",
    "lumi.title": "把角色宇宙塑造成 AI 原生产品闭环。",
    "lumi.lead": "Lumi Galaxy 是一个像素外星人桌面宠物网页世界，结合角色设计、世界观结构和 AI 辅助生产。",
    "lumi.overviewTitle": "产品视角",
    "lumi.overviewText": "Lumi Galaxy 是一个 AI 原生创意产品：5 个像素风格外星人桌面宠物，每个角色拥有独立世界观、性格设定、背景故事与互动方向，最终汇聚为可视化的“星球”网页。",
    "lumi.roleText": "我独立完成产品从 0 到 1 的定义与落地，包括产品形态定义、5 个外星人角色设定与世界观构建、交互体验设计、功能优先级排序、视觉方向、前端原型与后续迭代规划。",
    "lumi.decision1": "把项目定位为 AI 原生创意桌面宠物宇宙，而不是静态作品展示；每个角色都需要有明确性格、故事钩子和未来互动承诺。",
    "lumi.decision2": "使用 AI 工具批量生成 5 套角色背景故事、像素美术素材初稿与对话语料库，将原本需要美术与文案协作的内容生产环节压缩为单人可执行流程。",
    "lumi.decision3": "从产品构思、角色设定、技术选型到开发上线全流程独立完成，并持续围绕角色互动、页面表现和内容扩展方向迭代。",
    "lumi.executionTitle": "执行说明",
    "lumi.executionText": "该项目被设计为单人 0 到 1 工作流。AI 工具辅助创意发散、内容结构、网页实现与迭代，但产品方向始终保持角色、星球和世界观之间的视觉一致性。",
    "lumi.architectureTitle": "产品架构",
    "lumi.architectureText": "案例由视觉层、角色层和知识层共同构成。这个结构展示了它如何从作品集网页继续演化为带对话与持久记忆的 AI 伴侣产品。",
    "lumi.outcomeTitle": "结果",
    "lumi.outcomeText": "体现纯 AI 工具链单人完成创意产品从概念到上线的完整可行性，也体现创意产品 0 到 1 的头脑风暴能力、内容生产能力和网页落地能力。",
    "lumi.phase1Title": "定义世界与角色",
    "lumi.phase1Text": "建立像素外星人宇宙的人格系统、世界规则、视觉线索和互动承诺。",
    "lumi.phase2Title": "搭建角色内容系统",
    "lumi.phase2Text": "结构化角色背景、故事片段、视觉线索和对话语气，让每个外星人都有清晰可记忆的个性。",
    "lumi.phase3Title": "制作视觉与桌面原型",
    "lumi.phase3Text": "把概念转化为网页体验和桌面宠物包，补齐动效状态、菜单、安装说明和玩味但统一的视觉方向。",
    "lumi.phase4Title": "上线与迭代",
    "lumi.phase4Text": "将项目包装为已发布的独立实验，并定义下一轮方向：记忆、留存和更丰富的角色互动。",
    "lumi.navScope": "项目范围",
    "lumi.navProblem": "问题机会",
    "lumi.navStrategy": "产品策略",
    "lumi.navCharacters": "角色系统",
    "lumi.navWorkflow": "AI 工作流",
    "lumi.navRoadmap": "迭代路线",
    "lumi.metricCharacters": "像素外星人桌宠",
    "lumi.metricStates": "桌面行为状态",
    "lumi.metricIntents": "对话意图类别",
    "lumi.metricLaunch": "已上线网页案例",
    "lumi.scopeTitle": "项目范围",
    "lumi.scopeText": "这是一个独立项目，因此案例不写“我的角色”，而是写清楚项目范围：产品定义、角色系统设计、内容生产、原型实现、上线包装和下一阶段迭代规划。",
    "lumi.problemTitle": "问题与机会",
    "lumi.problemText": "很多桌宠产品在视觉上可爱，但系统厚度不足：它们可以出现在屏幕上，却很少拥有稳定人格、世界逻辑、对话风格和长期互动承诺。Lumi Galaxy 想验证一个小型 AI 原生角色宇宙，能不能让桌面陪伴更有记忆点、更可扩展。",
    "lumi.problemInsight1": "核心机会不是简单“做一个可爱的宠物”，而是搭建一个可复用的角色框架，支持不同人格、对话语气、视觉状态和未来记忆能力。",
    "lumi.problemInsight2": "第一版需要保持 MVP 边界：先验证世界观、角色差异、基础互动和上线包装，再扩展到更深的 AI 伴侣能力。",
    "lumi.strategyTitle": "产品策略",
    "lumi.strategyText": "第一版被定位为创意型 AI 伴侣原型，而不是完整效率工具。优先目标是验证角色、世界观和桌面/网页体验能否形成一个统一的产品方向。",
    "lumi.strategyCard1Title": "先验证宇宙感",
    "lumi.strategyCard1Text": "在加入复杂记忆和个性化之前，先定义世界观、角色集合、视觉识别和互动承诺。",
    "lumi.strategyCard2Title": "让角色真正不同",
    "lumi.strategyCard2Text": "每个桌宠都需要不同情绪节奏、说话风格和使用场景，避免变成一个通用助手套五个皮肤。",
    "lumi.strategyCard3Title": "保留扩展空间",
    "lumi.strategyCard3Text": "用数据化角色结构承载后续迭代：更多对话、持久记忆、更丰富桌面状态和主题角色扩展。",
    "lumi.charactersTitle": "角色系统",
    "lumi.charactersText": "角色层被设计成一个产品系统：每个外星人都有身份、人设、PAD 情绪基线、说话方式、视觉素材和对话方向。",
    "lumi.character1Title": "好奇探索者",
    "lumi.character1Text": "高好奇、轻盈活泼；短句、拟声词多，习惯把人类世界重新解释成外星逻辑。",
    "lumi.character2Title": "温柔照顾者",
    "lumi.character2Text": "节奏慢、语气柔和；适合低压力陪伴、喝水提醒和稳定的情绪支持。",
    "lumi.character3Title": "专注编程伙伴",
    "lumi.character3Text": "冷静、精确、带一点干幽默；适合工作时段、编程陪伴和安静的专注场景。",
    "lumi.characterTag1": "人格基线",
    "lumi.characterTag2": "PAD 情绪参数",
    "lumi.characterTag3": "对话意图分类",
    "lumi.characterTag4": "视觉状态资产",
    "lumi.characterTag5": "未来记忆钩子",
    "lumi.workflowTitle": "AI 生产工作流",
    "lumi.workflowText": "AI 工具被用于加速生产，但产品判断仍由人主导：产品应该是什么、角色如何形成差异、MVP 应该保留什么，以及哪些输出已经偏离世界观方向。",
    "lumi.workflowStep1": "概念与定位",
    "lumi.workflowStep2": "角色文案与美术初稿",
    "lumi.workflowStep3": "对话数据与前端原型",
    "lumi.workflowStep4": "人工筛选、统一方向与上线",
    "lumi.aiBuildText": "AI 辅助生成角色背景初稿、像素美术方向、对话变体、页面实现和迭代方案。",
    "lumi.myJudgmentText": "人的判断保留在选择层：定义产品边界、统一语气、淘汰不一致资产，并规划后续路线。",
    "lumi.arch1Title": "网页星球与桌面表层",
    "lumi.arch1Text": "公开网页案例和桌面宠物壳，让项目可访问、可分享，也方便外部快速理解。",
    "lumi.arch2Title": "可配置角色数据",
    "lumi.arch2Text": "角色档案、情绪基线、素材和对话规则与界面分离，方便未来继续扩展角色宇宙。",
    "lumi.arch3Title": "对话、菜单、状态与小游戏",
    "lumi.arch3Text": "体验中保留基础互动钩子，后续可以连接记忆、个性化和更丰富的 AI 行为。",
    "lumi.roadmapTitle": "迭代路线",
    "lumi.roadmapText": "路线图把已验证内容和下一步拆开呈现，让案例更像一个持续演进的产品，而不是一次性的视觉实验。",
    "lumi.roadmap1Title": "世界观、角色与网页",
    "lumi.roadmap1Text": "定义角色宇宙，完成可视化网页，让项目具备外部可读性。",
    "lumi.roadmap2Title": "桌宠与互动壳",
    "lumi.roadmap2Text": "支持桌面常驻、菜单、状态变化、安装说明和基础趣味互动。",
    "lumi.roadmap3Title": "对话与情绪响应",
    "lumi.roadmap3Text": "扩展意图识别、角色专属回复、PAD 情绪变化和小型互动闭环。",
    "lumi.roadmap4Title": "记忆与角色成长",
    "lumi.roadmap4Text": "加入用户偏好、长期记忆、关系进展和更丰富的伴侣行为。",
    "lumi.outcomeTag1": "已上线网页案例",
    "lumi.outcomeTag2": "桌面安装说明",
    "lumi.outcomeTag3": "角色数据模型",
    "lumi.outcomeTag4": "对话语料初稿",
    "lumi.outcomeTag5": "迭代路线图",
    "workflow.metaTitle": "AI Language Companion - Spanish Model | Ma Chen",
    "workflow.metaDescription": "马琛的 AI Language Companion - Spanish Model 项目案例。",
    "workflow.kicker": "案例研究 · AI Language Companion",
    "workflow.title": "AI Language Companion - Spanish Model",
    "workflow.lead": "一个围绕西语对话模型展开的 AI 语伴项目，聚焦语言学习场景、陪练语气、本地化质量与模型评估闭环。",
    "workflow.overviewTitle": "产品视角",
    "workflow.overviewText": "这个案例页将用于补充西语 AI 语伴模型的完整项目细节：目标用户场景、陪练 Persona、对话质量标准、双语本地化评审与模型迭代方式。",
    "workflow.roleText": "这里后续会补充具体工作范围、产品职责、模型评估 ownership 和本地化协作方式。",
    "workflow.decision1": "定义目标西语学习场景与对话质量标准。",
    "workflow.decision2": "设计语伴 Persona、纠错风格与双语评审流程。",
    "workflow.decision3": "建立围绕流利度、准确性、共情感、文化细节和难度适配的评估闭环。",
    "workflow.phase1Title": "定义学习场景",
    "workflow.phase1Text": "梳理日常会话、语法纠错、角色扮演、文化解释与信心建立等西语学习场景。",
    "workflow.phase2Title": "设计模型 Persona",
    "workflow.phase2Text": "定义语伴的语气、纠错方式、鼓励规则，以及它在导师、对话伙伴和文化解释者之间的边界。",
    "workflow.phase3Title": "建立评估闭环",
    "workflow.phase3Text": "围绕流利度、准确性、共情感、难度适配、文化细节和错误恢复能力建立评审标准。",
    "workflow.phase4Title": "补充项目细节",
    "workflow.phase4Text": "后续会继续加入模型样例、评估记录、Prompt 规则与本地化判断。",
    "workflow.architectureTitle": "模型工作流",
    "workflow.architectureText": "当前保留为模型工作流结构：场景输入、Persona 规则、回答生成、双语评审与迭代记录。",
    "workflow.executionTitle": "执行说明",
    "workflow.executionText": "这一页先作为西语模型项目壳保留，方便后续加入更具体的项目材料。",
    "workflow.outcomeTitle": "结果",
    "workflow.outcomeText": "一个预留好的 AI 语伴项目案例页，后续可承载模型样例、场景定义、评估标准与本地化决策。"
  }
};

Object.assign(translations.en, {
  "market.eyebrow": "Market range",
  "market.title": "Able to work across Europe, China, and Latin America.",
  "market.text": "Language fluency, cultural context, and localization judgment for products that need to travel well.",
  "projects.title": "Three product worlds, each given room to breathe."
});

Object.assign(translations.zh, {
  "market.eyebrow": "市场范围",
  "market.title": "能够覆盖欧洲、中国与拉丁美洲市场。",
  "market.text": "结合语言能力、文化语境与本地化判断，帮助产品跨市场成立。",
  "projects.title": "三个产品世界，各自拥有完整的展示空间。"
});

const capabilities = [
  {
    id: "01",
    enTitle: "AI product strategy",
    esTitle: "Estrategia de producto IA",
    zhTitle: "AI 产品策略",
    enText: "Problem framing, scenario design, prompt systems, and launch planning.",
    esText: "Definición de problema, diseño de escenarios, sistemas de prompt y planificación de lanzamiento.",
    zhText: "问题定义、场景设计、Prompt 系统与上线节奏。"
  },
  {
    id: "02",
    enTitle: "Localization and culture",
    esTitle: "Localización y cultura",
    zhTitle: "本地化与文化语境",
    enText: "Spanish, English, and Chinese product language with LATAM and EU sensitivity.",
    esText: "Lenguaje de producto en español, inglés y chino, con sensibilidad para LATAM y Europa.",
    zhText: "覆盖中文、英文、西语产品表达，并关注拉美与欧洲语境。"
  },
  {
    id: "03",
    enTitle: "User research",
    esTitle: "Investigación de usuarios",
    zhTitle: "用户研究",
    enText: "Interviews, persona synthesis, content analysis, and behavioral insight.",
    esText: "Entrevistas, síntesis de personas, análisis de contenido e insight de comportamiento.",
    zhText: "深度访谈、用户画像、内容分析与行为洞察。"
  },
  {
    id: "04",
    enTitle: "Interface storytelling",
    esTitle: "Narrativa de interfaz",
    zhTitle: "界面叙事",
    enText: "Visual hierarchy, case-study packaging, and product narrative design.",
    esText: "Jerarquía visual, presentación de casos y diseño narrativo de producto.",
    zhText: "视觉层级、案例包装与产品叙事设计。"
  }
];

function t(key, lang) {
  return translations[lang][key] || translations.en[key] || key;
}

function renderCapabilities(lang) {
  const root = document.querySelector("#capability-grid");
  if (!root) return;
  root.innerHTML = capabilities.map((item) => `
    <article class="capability-card">
      <span>${item.id}</span>
      <h3>${item[`${lang}Title`] || item.enTitle}</h3>
      <p>${item[`${lang}Text`] || item.enText}</p>
    </article>
  `).join("");
}

function setLanguage(lang) {
  document.documentElement.dataset.lang = lang;
  document.documentElement.lang = lang === "zh" ? "zh-CN" : lang;

  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.dataset.i18n, lang);
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((el) => {
    el.dataset.i18nAttr.split(",").forEach((pair) => {
      const [attr, key] = pair.split(":").map((value) => value.trim());
      if (attr && key) el.setAttribute(attr, t(key, lang));
    });
  });

  const titleEl = document.querySelector("title[data-i18n]");
  document.title = titleEl ? t(titleEl.dataset.i18n, lang) : t("meta.title", lang);
  renderCapabilities(lang);

  try {
    localStorage.setItem("site-lang", lang);
  } catch (error) {
    /* localStorage may be unavailable in some privacy modes */
  }
}

const savedLanguage = (() => {
  try {
    return localStorage.getItem("site-lang");
  } catch (error) {
    return null;
  }
})();

setLanguage(["en", "es", "zh"].includes(savedLanguage) ? savedLanguage : "en");

const toggle = document.querySelector(".lang-toggle");
if (toggle) {
  toggle.querySelectorAll("[data-lang-option]").forEach((button) => {
    button.addEventListener("click", () => {
      setLanguage(button.dataset.langOption);
    });
  });
}

(function initProjectReturnPosition() {
  const storageKey = "portfolio-return-position";
  const casePages = ["mbti-discussion.html", "lumigalaxy.html", "ai-workflow-gc.html"];
  const currentPage = window.location.pathname.split("/").pop() || "index.html";
  const isHome = currentPage === "index.html" || currentPage === "";

  if (isHome) {
    try {
      const saved = JSON.parse(sessionStorage.getItem(storageKey) || "null");
      if (saved && saved.restore) {
        sessionStorage.removeItem(storageKey);
        requestAnimationFrame(() => {
          window.scrollTo({ top: saved.scrollY || 0, behavior: "auto" });
        });
      }
    } catch (error) {
      sessionStorage.removeItem(storageKey);
    }

    document.querySelectorAll("a[href]").forEach((link) => {
      const targetPage = link.getAttribute("href").split("#")[0];
      if (!casePages.includes(targetPage)) return;
      link.addEventListener("click", () => {
        try {
          sessionStorage.setItem(storageKey, JSON.stringify({
            page: currentPage,
            scrollY: window.scrollY,
            restore: false
          }));
        } catch (error) {
          /* sessionStorage may be unavailable in some privacy modes */
        }
      });
    });
    return;
  }

  document.querySelectorAll('a[data-i18n="case.back"]').forEach((link) => {
    link.addEventListener("click", (event) => {
      try {
        const saved = JSON.parse(sessionStorage.getItem(storageKey) || "null");
        if (!saved || typeof saved.scrollY !== "number") return;
        event.preventDefault();
        saved.restore = true;
        sessionStorage.setItem(storageKey, JSON.stringify(saved));
        window.location.href = saved.page || "index.html";
      } catch (error) {
        /* Fall back to the normal link target. */
      }
    });
  });
})();

(function initReveal() {
  const targets = document.querySelectorAll(".reveal");
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  if (reduced || !("IntersectionObserver" in window)) {
    targets.forEach((target) => target.classList.add("is-visible"));
    return;
  }

  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add("is-visible");
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.18, rootMargin: "0px 0px -10% 0px" });

  targets.forEach((target) => observer.observe(target));
})();
